### ISSUE TITLE
Update RNPM linkage to v0.3.0

### ISSUE THREAD

**Issue by aviadhahami** [react-native-community/react-native-linear-gradient#103]
Hi
Since the latest [RN release, v0.30.0](https://github.com/facebook/react-native/releases/tag/v0.30.0) I've had to manually update my Android sources when migrating between versions in order to use the gradient component properly.
It seems that when using `$ rnpm link` it won't link the resources properly(not sure about iOS as I've tested only on Android).

couldn't find the script in this repo that runs on `$ rnpm link` and thus there's no PR.

Any available fixes?

**Comment by dgladkov** [comment]
Please use `react-native link` instead of rnpm. https://github.com/react-native-community/react-native-linear-gradient/commit/11d8fcd9ce23d7fe329957fa54a8cd9106110437
