### ISSUE TITLE
Transparent gradient

### ISSUE THREAD

**Issue by jreziga** [react-native-community/react-native-linear-gradient#104]
I tried to use a rgba color (with transparency) and it did not work well. Is it possible to have this feature ?

Thanks !

**Comment by gkrinc** [comment]
This works for me:

`<LinearGradient colors={[ 'transparent', 'red' ]} />`

and so does this

`<LinearGradient colors={['transparent', 'rgba(255, 0, 0, 1.0)', 'transparent']}/>`

I'm using LinearGradient v1.5.13

**Comment by nickhudkins** [comment]
Keep in mind that "transparent" is actually "transparent black" so you may be better off going from your `rgba(R, G, B, 1)` -> `rgba(R, G, B, 0)` transparent colors are indeed supported, but you may need to be more specific 👍
