### ISSUE TITLE
Android `error: cannot find symbol` for  `new LinearGradientPackage()`

### ISSUE THREAD

**Issue by josephan** [react-native-community/react-native-linear-gradient#106]
So I linked the package using RNPM but the gradient did not show. So I tried to add it manually and when I added `new LinearGradientPackage()` to `getPackages()` method in `MainApplication.java` the app would not build.

I am using rnpm version 1.9.0

Other than the gradient everything seems to be working fine.

```
  "dependencies": {
    "react": "15.2.1",
    "react-native": "0.29.1",
    "react-native-linear-gradient": "^1.5.12",
    "react-native-router-flux": "^3.31.0",
    "react-native-scrollable-tab-view": "^0.5.4",
    "react-native-swiper": "^1.4.8",
    "realm": "^0.14.1"
  }
```

Here is the error message:

```
~/mobile/appname/android/app/src/main/java/com/appname/MainApplication.java:29: error: cannot find symbol
          new LinearGradientPackage()
              ^
  symbol: class LinearGradientPackage
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by mobileDevNativeCross** [comment]
U did all of this? 
Android

in android/settings.gradle

...
include ':react-native-linear-gradient'
project(':react-native-linear-gradient').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-linear-gradient/android')
in android/app/build.gradle add:

dependencies {
   ...
   compile project(':react-native-linear-gradient')
}
and finally, in android/src/main/java/com/{YOUR_APP_NAME}/MainActivity.java for react-native < 0.29, or android/src/main/java/com/{YOUR_APP_NAME}/MainApplication.java for react-native >= 0.29 add:

//...
import com.BV.LinearGradient.LinearGradientPackage; // <--- This!
//...
@Override
protected List<ReactPackage> getPackages() {
 return Arrays.<ReactPackage>asList(
   new MainReactPackage(),
   new LinearGradientPackage() // <---- and This!
 );
}

**Comment by mienaikoe** [comment]
I'm also getting this problem, and have done all of these steps.

**Comment by mienaikoe** [comment]
I've also noticed that `react-native link react-native-linear-gradient` doesn't work for Android - only iOS

**Comment by georginio** [comment]
+1

**Comment by xgenvn** [comment]
I solved this by doing **react-native upgrade**

**Comment by ozzyknox** [comment]
I am building for Android and I'm getting this issue now with RV version 0.42.0. Is this possibly a breaking change with the latest version of RN or is there some other fix?

Please help.

**Comment by dgladkov** [comment]
You should not use `rnpm link` anymore, please consider switching to `react-native link`. It appears that the original problem happened because of incorrect linking, possibly caused by a missing import in `MainApplication.java`.

This issue is pretty old and probably related to `rpnm` usage, please create new issues if you encounter similar problems with the recent versions of the project.

**Comment by amlcodes** [comment]
I used react native link and am running into a similar issue

**Comment by dgladkov** [comment]
Reopening the issue. Could you please provide the following:
1. `react-native` and `react-native-linear-gradient` package versions.
2. Content of `MainApplication.java` file stripped of your project's sensitive data. If that's not possible, import section and `MainApplication.getPackages` method are enough.
3. Full compilation error message.

**Comment by zhaiyjgithub** [comment]
@dgladkov  I have done like this:
$:react-native link, 

result:

rnpm-install info Android module react-native-linear-gradient is already linked 
rnpm-install info iOS module react-native-linear-gradient is already linked 

$:react-native run-android

result:

A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-linear-gradient'.
      > Cannot create directory /..../node_modules/react-native-linear-gradient/android/build/intermediates/incremental/packageDebugAndroidTest/zip-cache

**Comment by amlcodes** [comment]
I apologize, I couldn't myself. I scrapped the branch. I believe it was stemming from another package but I went a different route so I removed it.
