### ISSUE TITLE
Images not appearing inside a gradient on Android

### ISSUE THREAD

**Issue by maxfurman** [react-native-community/react-native-linear-gradient#107]
node -v 6.2.0
react-native-cli 1.0.0
react-native 0.31.0

I'm trying to build a page where the background color has a gradient, and an image at the bottom of the page has a matching gradient as well. The following jsx works perfectly on ios but on android only the text is visible. Tested on emulator as well as a Galaxy S7.

```
<View style={styles.screenTwo}>
  <LinearGradient colors={['transparent', 'black']} start={[0.5, 0.5]}  style={styles.linearGradient}>
    <Image style={styles.screenTwoImage} source={require('./images/intro-screen-two.png')} >
      <LinearGradient colors={['transparent', 'black']} start={[0.5, 0.25]} style={styles.linearGradient}>
        <Text style={[styles.text, styles.skipText]} onPress={this.props.onSkip}>SKIP</Text>
      </LinearGradient>
    </Image>
    <Text style={[styles.text, styles.screenTwoText]}>SEE ALL OF THE STOCKS YOU WANT TO BE NOTIFIED ABOUT</Text>
  </LinearGradient>
  <Icon name="chevron-right" onPress={this.props.onNext} style={[styles.text, styles.nextArrow]} />
</View>
```

styles:

```
screenTwo: {
    flex: 1,
    backgroundColor: 'white',
    justifyContent: 'center',
    flexDirection: 'column'
  },
  screenTwoImage:{
    alignSelf: 'center',
    flexDirection: 'column-reverse'
  },
  screenTwoText: {
    fontSize: 30,
    color: 'black',
    fontWeight: 'bold',
    textAlign: 'center',
    paddingLeft: 25,
    paddingRight: 25,
    paddingBottom: 20
  },
  linearGradient: {
    flex: 1,
    flexDirection: 'column-reverse',
    backgroundColor: "transparent"
  }
```

the result on iOS:
<img width="376" alt="screen shot 2016-08-30 at 4 35 43 pm" src="https://cloud.githubusercontent.com/assets/6634694/18106038/d76ac5d6-6ecf-11e6-83f6-0f3f8c254369.png">

and on Android:
<img width="265" alt="screen shot 2016-08-30 at 4 40 43 pm" src="https://cloud.githubusercontent.com/assets/6634694/18106178/899be24e-6ed0-11e6-90a0-1905614ac0bb.png">

Thanks!

**Comment by charlesLin** [comment]
the same issue + 1

**Comment by bastarder** [comment]
same here + 1

**Comment by Sbphillips19** [comment]
same here +1

**Comment by radex** [comment]
Closing this, because a workaround exists: You can position another view on top of the gradient to make things look like they're inside the gradient.

I'd appreciate someone writing it up in the README.

Of course if you really want this, we accept PRs! :)
