### ISSUE TITLE
Use linear gradient for border color?

### ISSUE THREAD

**Issue by dsernst** [react-native-community/react-native-linear-gradient#113]
Is there a way to use this package to set border-color to a gradient?

**Comment by nickhudkins** [comment]
This would be a pretty serious undertaking, and currently this is not supported. I am not sure that it is really within "scope" of the project either as this is intended to simply "draw" a linear gradient.

**Comment by codinronan** [comment]
Easiest way to immediately accomplish the same effect: Nest one View within another View, with the "border with" being the padding on the outer container (or margin on inner). Then just wrap the inner View with the linear gradient, and make sure the inner View has a background color (anything besides 'transparent').

**Comment by pribeh** [comment]
Would be super cool to support gradient borders. The challenge with @codinronan's trick is that you cannot do transparent button backgrounds (and thus accomodate image based, multifarious or gradient backgrounds of containing views). Any ideas where one would start to alter LinearGradient to support truly gradient borders?

**Comment by radex** [comment]
I'm closing this since this is outside the scope of the library, and a simple workaround exists.

**Comment by IKTANIM** [comment]
Can please tell me what is the simple workaround @radex. I can't do transparent background can you please help.
