### ISSUE TITLE
RFC - Is it possible to incorporate this code in the Core React Native Code?

### ISSUE THREAD

**Issue by rturk** [react-native-community/react-native-linear-gradient#119]
I've glanced over the native `.java` and `.m` files and they look very straightforward. 

Do you think it will be possible to incorporate them in the main (core) react native code probably in the `View` Component.

This may also significantly reduce open issues since it will leverage the existing `View` component logic.

**Comment by dgladkov** [comment]
I was thinking about it, however current implementation uses props, which is okay for custom components, but doesn't feel right for general case of react-native Views which should be styled using RN Style. Considering that react-native already implements part of CSS spec, this functionality should be implemented as CSS linear-gradient function. Something like this:

```javascript
<View
style={{
  background: 'linear-gradient(135deg, red, blue)'
}}
/>
```

Or maybe more JS-like approach that will compile and memoize results, not sure how that will work with other background values though.

```javascript
<View
style={{
  background: StyleSheet.linearGradient(135, 'red', 'blue')
}}
/>
```

**Comment by rturk** [comment]
@dgladkov makes sense, props are only viable for custom componentes. IMO considering Web and RN best practices this should be implemented as a CSS spec.

**Comment by rturk** [comment]
Overall I think the important question is: What is the effort required to port this code into the core View Component.

**Comment by dgladkov** [comment]
That's hard to answer without thoroughly reading CSS linear-gradient spec, but before doing that it's better to open react-native issue and ask how does the core team feel about adding linear-gradient support and their opinion on how it should be implemented.

**Comment by sibelius** [comment]
let's keep this outside core
