### ISSUE TITLE
borderRadius does not contain gradient

### ISSUE THREAD

**Issue by administerspice** [react-native-community/react-native-linear-gradient#120]
"react-native-linear-gradient": "^1.5.14"
"react": "15.3.2"
"react-native": "0.36.0"

<LinearGradient colors={HUES}
                        style={styles.gradient}
        </LinearGradient>

gradient: {
    width: width-30, height: 15,
    borderWidth: 1, borderColor: '#eee', borderRadius: 15/2
  }

<img width="312" alt="screen shot 2016-10-31 at 4 20 36 pm" src="https://cloud.githubusercontent.com/assets/8702001/19870244/2ac1739c-9f86-11e6-8d39-6273d190a88a.png">

**Comment by miguelc1221** [comment]
In my case, it works for `borderRadius` but not 
`borderTopLeftRadius` 
`borderTopRighttRadius` 
`borderBottomRightRadius` 
`borderBottomLeftRadius`

**Comment by radex** [comment]
Hey! I'm closing this since this is a stale issue. If you believe it's still relevant to fix, post a comment and I'll reopen.

**Comment by dukeeagle** [comment]
Hi there,

I'd love to see this fixed. Exact same issue.

**Comment by Marguelgtz** [comment]
had the same issue a couple times now, hopefully this issue gets open again
