### ISSUE TITLE
setNativeProps breaks `Animated` support

### ISSUE THREAD

**Issue by Benmidi** [react-native-community/react-native-linear-gradient#122]
Hi,

With 890fd18 this component was modified to allow use in TouchableHighlight, etc. This broke support for passing this component to Animated.createAnimatedComponent.

<img width="487" alt="screen shot 2016-11-08 at 4 23 28 pm" src="https://cloud.githubusercontent.com/assets/813586/20117885/6aae5150-a5d0-11e6-8ba6-e5c859e10a0b.png">

RN: 0.37
macOS: 10.12.1
iOS: 10.1

**Comment by dgladkov** [comment]
I found a relevant issue in other project: https://github.com/oblador/react-native-vector-icons/issues/337#issuecomment-259187815. Could you please verify that the proposed solution works?

**Comment by Benmidi** [comment]
Thanks that worked! It appears oblador has a PR in the ReactNative repo to resolve this more broadly :) https://github.com/facebook/react-native/pull/10827

**Comment by patrickhaug** [comment]
Would it be / is it / possible to pass interpolated color values to the color prop when wrapped in animated component? I do not get it to work. Is this related?

**Comment by dgladkov** [comment]
This is fixed in react-native>=0.38.0 by https://github.com/facebook/react-native/commit/7b2ee7119a56054edf1425cda31649c4d0490c23
