### ISSUE TITLE
borderTopLeftRadius not supported in iOS

### ISSUE THREAD

**Issue by imarem** [react-native-community/react-native-linear-gradient#126]
In iOS LinearGradient only support borderRadius, per corner is not supported.

Any plans to support this feature in iOS?

Thanks!!

**Comment by ajonno** [comment]
i REALLY need this to for a project we're working on now. Any assistance would be great, or tips on forking and making the changes ourselves ?

**Comment by ATranDev** [comment]
You can add " .   overflow: 'hidden'    " to the style that works

**Comment by radex** [comment]
Hey! I'm closing this since it looks like a solved issue.
