### ISSUE TITLE
Gradient over text

### ISSUE THREAD

**Issue by moiri-gamboni** [react-native-community/react-native-linear-gradient#133]
Hello,

I am trying to have a gradient partially obscuring some text, however it always displays in the background right now. Is something like this possible?
![image](https://cloud.githubusercontent.com/assets/3668735/21490745/df3bb04c-cc29-11e6-98bd-050123913719.png)
Thank you for your help
EDIT: Is this the same as #56?

**Comment by javamonn** [comment]
Creating a gradient like the one seen in the image appears to already be possible, at least on Android: 

```
<View>
   <Text>Text to be obscured by gradient...</Text>
   <LinearGradient
     colors={['transparent', '#some-gray-ish-color']}
     style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 }}
   />
</View>
```

This results in the desired text behind the gradient effect, rather than having the gradient behind the text.

**Comment by radex** [comment]
Hey! I'm closing this since it looks like a solved issue.

**Comment by mayconmesquita** [comment]
If you need fade in from white.

![Screenshot](https://user-images.githubusercontent.com/46308804/87883931-30b1ba80-c9e1-11ea-9976-b0c57193b8dc.png)

I'm using this code to get this result:

```js
<View style={[styles.descriptionContainer, { maxHeight: 140 }]}>
  <Text style={styles.descriptionHeading}>Descrição do Produto</Text>
  <Text style={styles.descriptionText}>{ description }</Text>

  <LinearGradient
    colors={['transparent', 'rgba(255,255,255,1)']}
    start={{x: 0, y: .5}}
    end={{x: 0, y: 1}}
    style={styles.linearGradientContainer}
  />
</View>

const styles = {
  descriptionContainer: {
    flex: 1,
    overflow: 'hidden',
  },
  descriptionHeading: {
    marginTop: 20,
    marginBottom: -15,
    fontSize: 21,
    color: '#212121',
  },
  descriptionText: {
    fontSize: 15,
    color: '#6f6f6f',
  },
  linearGradientContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
}
```

**Comment by andreialecu** [comment]
A better solution, if you can use https://github.com/react-native-masked-view/masked-view:

```ts
  <MaskedView
    maskElement={
      <LinearGradient
        style={StyleSheet.absoluteFill}
        colors={['white', 'transparent']}
        start={{x: 0, y: 0.5}}
        end={{x: 0, y: 1}}
      />
    }
  >
    <Text>{item.summary}</Text>
  </MaskedView>


```

The benefit is that it works well for dark, or even image backgrounds as well.

<img width="395" alt="Screenshot 2021-04-02 at 12 18 30" src="https://user-images.githubusercontent.com/697707/113402349-8aaab280-93ad-11eb-912e-0a78121a4782.png">
