### ISSUE TITLE
Warning Failed prop type Tried to merge an object, instead got 0,0 in Linear Gradient

### ISSUE THREAD

**Issue by krzysztofp** [react-native-community/react-native-linear-gradient#136]
I've used the newest 1.6.2 version, got this warning and couple more today:
![image](https://cloud.githubusercontent.com/assets/1634660/21606648/2be50f60-d1b1-11e6-8fac-532397d03488.png)

Other warnings are similar:
![image](https://cloud.githubusercontent.com/assets/1634660/21606669/46b1c6bc-d1b1-11e6-888d-59701ce76008.png)

**Comment by tobiaslins** [comment]
Hi,

They changed the syntax of start & end..

It can be easily resolved

```js
<LinearGradient
  start={{x: 0.0, y: 1.00}} 
  end={{x: 1.0, y: 0.0}}
  colors={['#202025', '#353a54']}
  style={styles.gradient}
/>
```

My old code was: 

```js
<LinearGradient
  start={[0, 1]}
  end={[1, 0]}
  colors={['#202025', '#353a54']}
  style={styles.gradient}
/>
```

**Comment by dgladkov** [comment]
@tobiaslins is right. This change was made in accordance with a change in React Native in a backwards compatible way: even though you receive warnings, old syntax still works, hence no major version bump.
