### ISSUE TITLE
Error while updating prop end

### ISSUE THREAD

**Issue by rigobcastro** [react-native-community/react-native-linear-gradient#139]
react-native: 0.37.0
react-native-linear-gradient: 1.6.0

![screenshot_1483673415](https://cloud.githubusercontent.com/assets/1006483/21706649/dd84aafa-d396-11e6-91b3-28167ed13671.png)

I don't know where or why its happen, thanks for your support!

**Comment by HeinZawHtet** [comment]
Syntax changed for start & end props.
Instead of 
`start={[0, 0]} end={[1, 0]}`
Try
`start={{x: 0, y: 0}} end={{x: 1, y: 0}}`

**Comment by rigobcastro** [comment]
@HeinZawHtet Thanks!
