### ISSUE TITLE
Only red border is visible on iOS

### ISSUE THREAD

**Issue by elayabharath** [react-native-community/react-native-linear-gradient#143]
![image](https://cloud.githubusercontent.com/assets/4365353/22037461/39fb4da4-dd1d-11e6-8665-16ed7e9be869.png)

On iOS, "react-native-linear-gradient": "^2.0.0".

Tried all ways of linking library (react-native link, cocoapods, manuall linking), no luck. Any pointers on how I can get this working?

**Comment by RichardLindhout** [comment]
Have you already build your project again via xCode?

**Comment by danharper** [comment]
@elayabharath if you're using React Native 39 or below, use `^1.6.2` of this plugin - v2 is for RN 40+.

**Comment by GR4VEZ** [comment]
I have also followed all steps in manual linking, including that of pulling directly from the repo. React Native is up to .40 and I am indeed running 2.0. 

Only red border here as well.

**Comment by JonnyBurger** [comment]
I simply forgot to recompile the project after it was linked.
It adds a native dependency, so Live Reloading is not enough.

**Comment by jacks205** [comment]
Still getting a red border on new projects using:

`react-native link`

and my package.json
```
"react-native": "0.41.2",
"react-native-linear-gradient": "^2.0.0"
```

**Comment by NoNameProvided** [comment]
Does this solved now? I just started to play react-native a hour ago, and I cannot add this module doesn't matter how I try. 

I have installed it, linked it, restarted the packager, still I only see the red border. I am on react-native: 0.41.2. How should I fix this?

**Comment by mosesmc52** [comment]
Did anyone figure out how to fix this issue?

**Comment by abeauvois** [comment]
Solved in my case with RN 0.41.2: run this command in the terminal 'react-native run-ios'  for recompiling (necessary in general after a 'react-native link' command)

**Comment by dgladkov** [comment]
Just tested it on a new project with RN@0.42.3, works for me. Please keep in mind that the project uses a native component, so correct install steps should be:
1. `npm install react-native-linear-gradient`
2. `react-native link`
3. `react-native run-android` or/and `react-native run-ios`

If you still experience problems, try to restart React Native packager with `npm run start`.

Feel free to reopen the issue if my proposed solution does not work for you.

**Comment by yash2code** [comment]
@dgladkov doesn't work with CRNA

**Comment by saman** [comment]
I'm using `react-native` version `0.46.1` but this package does not work and it draw a red border box.

**Comment by bumkaka** [comment]
0.46.4, android - red border

**Comment by nakul12345** [comment]
0.47.1, android - red-border

**Comment by chrisOberon** [comment]
I have the same issue, like nakul, I am on 0.47.1

**Comment by DanteEvil** [comment]
I'm on 0.48.2, I tried all the solutions mentioned above but no luck, still red border only.

**Comment by Unlighten** [comment]
I'm on 0.48.2, I tried everything also. Still no luck. Still getting a red border.

**Comment by DanteEvil** [comment]
@Unlighten , I'm on 0.50.3 and it works fine. The problem occurs just because I don't link the lib to my iOS project. Running 'react-native link' has fixed my problem.

**Comment by Unlighten** [comment]
@DanteEvil I am using expo and haven't detached my project and I tried react-native-link and it didn't work for me. My issue was that images were not loading quickly enough, but after taking my project out of development mode, the images loaded 10x faster. I have this package working, but I had a very similar issue with another package showing a red border and jumped on here to see if I could find the problem. Thanks for your guys help!
