### ISSUE TITLE
Does it support View props?

### ISSUE THREAD

**Issue by grundmanise** [react-native-community/react-native-linear-gradient#146]
Hello, thank you for such a great & useful package!
Wanted to know, does LinearGradient extends View, does it support View props?

**Comment by dgladkov** [comment]
Thank you for reporting the issue!

View props were supported since the project's very first version, however it appears that README does not mention that.

Fixed by https://github.com/react-native-community/react-native-linear-gradient/commit/df8ce9569d0729d683a385fe081220c8efe8dc66
