### ISSUE TITLE
Can't find this <React/RCTViewManager.h>

### ISSUE THREAD

**Issue by serbol** [react-native-community/react-native-linear-gradient#147]
In case if I replace #import <React/RCTViewManager.h> to #import "RCTViewManager.h" everything is OK!!!
iOS developers help me! What wrong with it?

**Comment by ocleo1** [comment]
Got same issue here. Then I tried this and resolved it. https://github.com/facebook/react-native/issues/12042#issuecomment-275025960

**Comment by serbol** [comment]
Yes could be fixed by adding this construction to BVLinearGradientManager.h:
```
#if __has_include(<React/RCTViewManager.h>)
#import <React/RCTViewManager.h>
#elif __has_include("RCTViewManager.h")
#import "RCTViewManager.h"
#else
#import "React/RCTViewManager.h"   // Required when used as a Pod in a Swift project
#endif
```

**Comment by rh389** [comment]
Are you using an older version of react native?

If you're using React Native < 0.40 you'll want to use v1.x of this package (`npm install --save react-native-linear-gradient@^1.6.2`). v2.x is for RN >=0.40. At this point that's really the only difference between the two.

**Comment by dgladkov** [comment]
Sorry, but I am closing this issue. Please refer to https://github.com/react-native-community/react-native-linear-gradient/pull/150#issuecomment-290373936 for explanation.
