### ISSUE TITLE
[IOS] Handle this failed error on 0.40

### ISSUE THREAD

**Issue by Fantasim** [react-native-community/react-native-linear-gradient#148]
Hi,

I've just updated react-native to version 0.40 by also updating react-native-linear-gradient, and by building, I get this error, how do I solve it?

http://www.yagoshack.fr/?v=capturgeg.png

**Comment by nillo** [comment]
see this post https://github.com/magus/react-native-facebook-login/issues/216#issuecomment-283285390

So for this plugin this would mean
Libraries/BVLineadGradient.xcodeproj <-- within your main project  (xcode)

BVLinearGradient.h
```
#import <UIKit/UIKit.h>
#import <React/RCTView.h>
```

BVLinearGradient.m
```
#import "BVLinearGradient.h"
#import <React/RCTConvert.h>
#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>
```

BVLinearGradientManager.h
```
#import <React/RCTViewManager.h>
```

BVLinearGradientManager.m
```
#import "BVLinearGradientManager.h"
#import "BVLinearGradient.h"
#import <React/RCTBridge.h>
```

Hope this helps, 
As i said in my other post, i don't have time to make Pr's at this moment, maybe later, but maybe u can do this!

Hope this helps 

greetz
