### ISSUE TITLE
Definition of how the X, Y coordinates work? 

### ISSUE THREAD

**Issue by ajonno** [react-native-community/react-native-linear-gradient#152]
hey folks, i need to incorporate linear gradient into our app but have zero clue how the start/end/x/y coordinates in this library affect the gradient color output. Is there a description anywhere of how to use them or better still can some documentation be added to this repo ? 

This is an example provided by our graphic designers.
![2017-03-01_10-42-01](https://cloud.githubusercontent.com/assets/3005269/23439691/fabc493e-fe6b-11e6-8df3-58ed669073f0.png)

**Comment by ajonno** [comment]
actually i just found this on Exponent's site. sweet! can it be added to this repo's readme too ?

props

colors
An array of colors that represent stops in the gradient. At least two colors are required (otherwise it's not a gradient, it's just a fill!).

start
An array of [x, y] where x and y are floats. They represent the position that the gradient starts at, as a fraction of the overall size of the gradient. For example, [0.1, 0.1] means that the gradient will start 10% from the top and 10% from the left.

end
Same as start but for the end of the gradient.

locations¶
An array of the same lenth as colors, where each element is a float with the same meaning as the start and end values, but instead they indicate where the color at that index should be.

« KeepAwake Location »

**Comment by dgladkov** [comment]
The issue was resolved by https://github.com/react-native-community/react-native-linear-gradient/pull/153

 Props to @ajonno for reporting the issue and submitting PR!
