### ISSUE TITLE
Not work properly on Android with react-native 0.42.0

### ISSUE THREAD

**Issue by Finnsun** [react-native-community/react-native-linear-gradient#155]
When I add it to project, it only shows a red border with white content. I'm sure that I have linked the libraries correctly.

**Comment by robertmylne** [comment]
Not working for me either

**Comment by Finnsun** [comment]
@robertmylne Are you using 'react-native-navigation' ? It seems that they can‘t work together. I build a new project without 'react-native-navigation' and it works.

**Comment by ricking06** [comment]
Same for me a red border only

**Comment by robertmylne** [comment]
I ended up getting it working.

**Comment by jjhesk** [comment]
@robertmylne how did that work?

**Comment by Vlad-Zhukov** [comment]
You have to rebuild the app to make it work.

**Comment by andrerfneves** [comment]
As @Vlad-Zhukov said, just rebuild it and it should work! Tested today on brand new React Native Android application using RN 0.42.3

**Comment by dgladkov** [comment]
Just tested it on a new project with RN@0.42.3, works for me. Please keep in mind that the project uses native components, so correct install steps should be:
1. `npm install react-native-linear-gradient`
2. `react-native link`
3. `react-native run-android` or/and `react-native run-ios`

If you still experience problems, try to restart React Native packager.

Feel free to reopen the issue if you still experience the problem.
