### ISSUE TITLE
Warning: Native component for "BVLinearGradient" does not exist

### ISSUE THREAD

**Issue by msutyak** [react-native-community/react-native-linear-gradient#157]
I have followed all of the steps in the documentation.  I am getting this error in iOS.  

Using:

import LinearGradient from 'react-native-linear-gradient';

**Comment by peterorum** [comment]
I got this but had missed the step:
Add libBVLinearGradient.a to Build Phases -> Link Binary With Libraries.

**Comment by dgladkov** [comment]
Please keep in mind that the project uses a native dependency and you need to rebuild the app for the gradient to work. Also, make sure that you use latest version of `react-native-cli` package before linking.

Refer to this comment for possible solutions: https://github.com/react-native-community/react-native-linear-gradient/issues/143#issuecomment-290397879.

**Comment by kuldeepoza14** [comment]
You have to run project for solve this error.
react-native run-android

**Comment by eflatz** [comment]
For IOS I had to manually set up dependencies as described in the [readme](https://github.com/react-native-community/react-native-linear-gradient) and it works.

**Comment by rahulbhankar786** [comment]
thanks @kuldeepoza14
