### ISSUE TITLE
Unable to resolve path to module

### ISSUE THREAD

**Issue by GregTheGreek** [react-native-community/react-native-linear-gradient#158]
I've followed the instructions in the docs, but eslint keeps telling me this error:
`Unable to resolve path to module 'react-native-linear-gradient'`

And when I apply a dark blue ->  slightly lighter blue, I get a white background and it adds roughly a 
`paddingRight: 30` ?

**Comment by peterorum** [comment]
I think eslint gives a warning because it's an actual native (xcode) component rather than js. So I disable the warning for that line.

**Comment by sibelius** [comment]
link error
