### ISSUE TITLE
Error Message when installing this on Android

### ISSUE THREAD

**Issue by JeffreyLeeSpokeo** [react-native-community/react-native-linear-gradient#159]
I keep getting this error message:
Error:Project :app declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :react-native-linear-gradient.

I searched online and people mentioned something about not being able to find this android folder in the react-native-linear-gradient folder in node_modules. I searched for it and the android folder is there. But I still have this issue. What should I do?

**Comment by dgladkov** [comment]
Project's path for gradle build is located in `./android/settings.gradle`. It should look like this:

```groovy
...

include ':react-native-linear-gradient'
project(':react-native-linear-gradient').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-linear-gradient/android')

...
```

Also, please check https://github.com/react-native-community/react-native-linear-gradient/issues/143#issuecomment-290397879 for detailed installation steps and consider recreating the project from scratch.

**Comment by sibelius** [comment]
link error
