### ISSUE TITLE
not working on android RealPhone, only "Red border" .But Genymotion Emulator is OK.

### ISSUE THREAD

**Issue by pengfeiyan** [react-native-community/react-native-linear-gradient#162]
thank you for helping.

Gradient is working well on Genymotion Emulators.  (version 4.1-7.0)
but not working on android RealPhone. (my test phone is android version5.0 / 6.0 )
only "Red border" was displayed.

would you  give me some advices? thank you.
![error](https://cloud.githubusercontent.com/assets/24911989/24783813/94af6a1e-1b89-11e7-9823-7e309a444db0.png)

**Comment by aferrerallu** [comment]
I'am experiencing the same red border and no gradient.
I start having this problem after I updated react native changing package.json to 0.43.
Also I run `react-native upgrade`.

I got this warnings on `npm install`

```npm WARN react-native-grid-component@1.0.6 requires a peer of react@>=15.3.1 but none was installed.
npm WARN react-static-container@1.0.1 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 but none was installed.
npm WARN react-test-renderer@15.4.2 requires a peer of react@^15.4.2 but none was installed.```

**Comment by pengfeiyan** [comment]
@aferrerallu 
thank you for your infomation.

Was gradient OK before react-native v0.43 ?
is it will be ok by downgrading the react-native ?

**Comment by MyTotoro** [comment]
Yea, i'm seeing the same red borders - I can't confirm if it works on genymotion

"react": "~15.4.1",
    "react-native": "0.42.0",

**Comment by MyTotoro** [comment]
Ahh, I had to close simulator and re-run react-native run-android

**Comment by pengfeiyan** [comment]
I reinstalled the React Native V0.43 on system, and recreated a new project , 
then copied all sources from old project (react-native 0.39).

to my surprise,
it is working well , not only on Genymotion , but also RealPhone.
