### ISSUE TITLE
Warning about refs when testing my components with Jest

### ISSUE THREAD

**Issue by Strayer** [react-native-community/react-native-linear-gradient#164]
I included react-native-linear-gradient in one of my components and now receive the following warning when running the jest test suite:

```
$ jest
 PASS  __tests__/App.js
  App
    ✓ should render correctly (40ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        0.728s, estimated 1s
Ran all test suites.
  console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:71
    Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.

    Check the render method of `LinearGradient`.
        in Unknown (created by LinearGradient)
        in LinearGradient (created by App)
        in View (created by View)
        in View (created by App)
        in App

✨  Done in 1.38s.
```

I couldn't find out why this is happening, googling also didn't help. The Jest snapshot seems fine, I also don't see any warnings when running the app, so it seems like this is only happening in the test environment…

I created an example app that shows this behaviour and pushed it to GitHub: https://github.com/Strayer/react-native-LinearGradientTestWarning

Steps to reproduce:
1. `git clone https://github.com/Strayer/react-native-LinearGradientTestWarning.git`
2. `cd react-native-LinearGradientTestWarning`
3. `yarn install`
4. `yarn test`

**Comment by peterorum** [comment]
In __mocks__, create react-native-linear-gradient.js, with content:

```
import { View } from 'react-native';

export default View;
```

**Comment by koenpunt** [comment]
Instead of exporting a `View`, export a string and jest uses that as the component name:

```js
export default 'BVLinearGradient';
```
