### ISSUE TITLE
'React/RCTView.h' file not found; 'React/RCTViewManager.h' file not found

### ISSUE THREAD

**Issue by msutyak** [react-native-community/react-native-linear-gradient#165]
<img width="261" alt="screen shot 2017-04-12 at 8 54 56 pm" src="https://cloud.githubusercontent.com/assets/3487153/24989560/5789329a-1fc2-11e7-9ebd-a9086cdcc610.png">

I am getting this error, despite me following the instructions to a T.  I am using RN-42, I have added the correct target paths:

<img width="1252" alt="screen shot 2017-04-12 at 8 56 41 pm" src="https://cloud.githubusercontent.com/assets/3487153/24989600/93f51e06-1fc2-11e7-914c-6869d3943756.png">

I am using this in packages.json:

"react-native-linear-gradient": "react-native-community/react-native-linear-gradient"

Very frustrating.  What is happening?

**Comment by SirVeryBritish** [comment]
Stil happening in 2.3.0

**Comment by 12343954** [comment]
+1

**Comment by sunb123** [comment]
I get the same error. RN 0.52.2

**Comment by sunb123** [comment]
I fixed this issue for me. Check your build scheme.

**Comment by agates4** [comment]
"Check your build scheme" you couldn't have picked something more ambiguous to say than that. what is the fix?

**Comment by nicholasc** [comment]
I get this when I add `use_frameworks!` to my Podfile

**Comment by timotew** [comment]
Re-running `$ pod install` in the ios folder fixed it for me. My mistake, I added a dependency to the pod file and it affected the libraries generated so I removed it and run `pod install`.

**Comment by atom2ueki** [comment]
I also have `use_frameworks!` in my `Podfile`, I get the same error. RN 0.52.0, one laptop no issue with pod version 1.3.1, but with pod version 1.5.0, got this error.

**Comment by christophby** [comment]
Try to remove your `Pods` directory and do a `pod install` again.

**Comment by aliszafar1** [comment]
+1

**Comment by wmonecke** [comment]
Happening here too. Removing Pods folder didn't do anything.

**Comment by rocaiguina** [comment]
I am stuck with this issue also.  
'Duplicate module name: react-native error' when using run-ios
'React/RCTView.h' file not found; 'React/RCTViewManager.h' file not found when building in Xcode

I find it odd that the pod is installed as a Development Pod

tried to install manually ( both options ) and with link with no luck.
Anybody has a workaround? Maybe erase one of the duplicates
thanks

**Comment by rocaiguina** [comment]
Got it working.  I was making the mistake of doing react-native link, instead of react-native link react-native-linear-gradient

**Comment by asifalikhokhar** [comment]
any solution ? I am getting 'React/RCTView.h' file not found in BVLinearGradient.h


`platform :ios, '11.0'
use_frameworks!

target 'myapp' do

pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
end

`

**Comment by ismnoiet** [comment]
To solve this issue add the following before `pod 'BVLinearGradient'`:
```
pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'DevSupport',
  'RCTNetwork',
  'RCTWebSocket'
]

# then here you can add BVLinearGradient
pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

 # this is needed to avoid including multiple references to react.
 post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
```

then delete Pods folder and try to install again
```
rm -rf Pods/ && pod install
```

At this point kill your running package manager, clean the project on Xcode, run again and it should work.

**Comment by davojan** [comment]
For me finally worked this magic:

```
# if you have old version or have tried manual linking react-native-linear-gradient
react-native unlink react-native-linear-gradient
cd ios
# we need to delete Podfile to tell react-native link to link in usual way
rm -rf Pods Podfile Podfile.lock
cd ..
# this will correctly link linear-gradient without any pod magic
react-native link react-native-linear-gradient
cd ios
git reset HEAD Podfile Podfile.lock
pod install
```
Main idea is to link module without cocoa pods. It happens when no Podfile exists in project. Hope this will help.

Message to maintainers: installation via cocoapods should be either removed or carefully tested and fixed. It just doesn't work in any way. Too many hours wasted :(

**Comment by coolvijay89** [comment]
> To solve this issue add the following before `pod 'BVLinearGradient'`:
> 
> ```
> pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
> pod 'React', :path => '../node_modules/react-native', :subspecs => [
>   'Core',
>   'DevSupport',
>   'RCTNetwork',
>   'RCTWebSocket'
> ]
> 
> # then here you can add BVLinearGradient
> pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
> 
>  # this is needed to avoid including multiple references to react.
>  post_install do |installer|
>     installer.pods_project.targets.each do |target|
>       if target.name == "React"
>         target.remove_from_project
>       end
>     end
>   end
> ```
> then delete Pods folder and try to install again
> 
> ```
> rm -rf Pods/ && pod install
> ```
> At this point kill your running package manager, clean the project on Xcode, run again and it should work.

This is work like a charm. Thank you @ismnoiet

**Comment by wjohnw6** [comment]
For me work only manual linking. Following this [steps](https://facebook.github.io/react-native/docs/linking-libraries-ios)

**Comment by lvlrSajjad** [comment]
Same problem
In my system with the same version of Xcode and node app builds and runs successfully 
But in the app center getting this error:
```
...unners/2.160.0/work/1/s/node_modules/react-native-linear-gradient/BVLinearGradient/BVLinearGradient.h:1:9: fatal error: 'React/RCTView.h' file not found
#import <React/RCTView.h>
        ^~~~~~~~~~~~~~~~~
1 error generated.
```

My react-native version is 0.61.3 and I use auto-linking for all of my native libraries

**Comment by lvlrSajjad** [comment]
I also tried manual linking
This time build error happened even in my side
```
... ded from /Users/lvlrx/Coding/Farhad kazemy - Appozitory/Magny/github/magny-react-app/node_modules/react-native-linear-gradient/BVLinearGradient/BVLinearGradientManager.m:1:
/Users/lvlrx/Coding/Farhad kazemy - Appozitory/Magny/github/magny-react-app/node_modules/react-native-linear-gradient/BVLinearGradient/BVLinearGradientManager.h:1:9: fatal error: 'React/RCTViewManager.h' file not found
#import <React/RCTViewManager.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by urska19** [comment]
Unlinking and relinking solved the issue for me.

**Comment by yusufozcan** [comment]
I tried many alternatives for rtmp stream viewing. All libraries producing an error like `RCT..... was not found`. 

For me, the problem was with flutter. I don't know what exactly flutter is. I guess it is a debugger extension. Anyway, in podfile there is some codes like below.


**podfile**
```
...
# Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
add_flipper_pods!
post_install do |installer|
       flipper_post_install(installer)
end
```

But this kind of libraries inserting or wants you to insert `use_frameworks!` line to your pod file. In the commented section of above code, it says if you have `use_frameworks!` line, disable flutter installation. Then I decided to remove everything related with flutter. From podfile and AppDelegate.m file. Then finally I was able to solve my problem.
