### ISSUE TITLE
How to make complex gradient on Navbar?

### ISSUE THREAD

**Issue by ChaoTzuJung** [react-native-community/react-native-linear-gradient#166]
#<img width="275" alt="2017-04-18 1 47 07" src="https://cloud.githubusercontent.com/assets/22141289/25098599/c89391fc-23db-11e7-87bd-97256a3b7d7d.png">

**Comment by DevManny** [comment]
check this link: https://github.com/react-native-community/react-native-linear-gradient#locations

**Comment by benjdlambert** [comment]
IMO, creating that with this library would be extremely difficult. 

It looks actually more like a an image blur than a gradient.

Maybe something like this could help:
https://github.com/react-native-community/react-native-blur

**Comment by radex** [comment]
Hey! I'm closing this since this is a stale issue. If you believe it's still relevant to fix, post a comment and I'll reopen.
