### ISSUE TITLE
Using linear gradient only shows red border around element

### ISSUE THREAD

**Issue by axelphunter** [react-native-community/react-native-linear-gradient#167]
I've just added Linear gradient to my project but it only seems to be adding a red border.

http://tinypic.com/r/2s6oab6/9

Code is as follows

```
import React from 'react';
import {
  AppRegistry,
  StyleSheet,
  View,
} from 'react-native';
import LinearGradient from 'react-native-linear-gradient';

const App = () => (
  <LinearGradient
    colors={['red', 'blue']}
    style={styles.gradient}
  />
);

const styles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
});

AppRegistry.registerComponent('DiCEMobile', () => App);
```

**Comment by yogeshmoradiya121** [comment]
same issue

**Comment by rexlow** [comment]
same here

**Comment by axelphunter** [comment]
Actually turns out that the lineargradient package wasn't included in the Xcode project. Check your app logs and go through the manual installation process.

**Comment by yogeshmoradiya121** [comment]
I have faced this issue on android

**Comment by nbluis** [comment]
Try link the project dependencies again.
`react-native link`

This solves my issue.
