### ISSUE TITLE
View.propTypes is deprecated

### ISSUE THREAD

**Issue by skv-headless** [react-native-community/react-native-linear-gradient#170]
Using View.PropTypes is deprecated since 0.44.0.  facebook/react-native@53905a537a58d028fc5eb1c4e9a8ec967d8cd396
**This is a breaking change through**, it will require the latest react-native@0.44.0 installed.

**Comment by mimiyan056** [comment]
I also use the react-native-linear-gradient component
Chrome Debug > Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.

please help me, thks~

**Comment by mimiyan056** [comment]
RN 0.44.0
(anonymous)	@	node_modules\react-native-linear-gradient\index.android.js:45

**Comment by jayarprado** [comment]
Having the same issue. Hope this gets fixed soon.
