### ISSUE TITLE
When I try to make a gradient it makes a 1 pixel thick red outline instead? [Android]

### ISSUE THREAD

**Issue by anchpop** [react-native-community/react-native-linear-gradient#175]
![image](https://cloud.githubusercontent.com/assets/3711047/26661866/3e106aa6-464e-11e7-9bbb-72a65d3c4735.png)

And here is my code, basically taken directly from the readme

```
    return (
      <LinearGradient colors={['#4c669f', '#3b5998', '#192f6a']} style={{flex: 1,
                                                                        paddingLeft: 15,
                                                                        paddingRight: 15,
                                                                        borderRadius: 5}}>
        <Text style={{fontSize: 18,
                      fontFamily: 'Gill Sans',
                      textAlign: 'center',
                      margin: 10,
                      backgroundColor: 'transparent'}}>
          Sign in with Facebook
        </Text>
      </LinearGradient>
    )
```

Any and all help would be very appreciated!

**Comment by anchpop** [comment]
Also, replacing `flex: 1` with `width: 400, height: 200,` gives a more clear effect:

![image](https://cloud.githubusercontent.com/assets/3711047/26661950/d4ca62e4-464e-11e7-966a-b9ba51cc5c63.png)

It seems a red border appears around my component, instead of a gradient

**Comment by sicksbyproxy** [comment]
I'm having the exact same problem

**Comment by zakster12** [comment]
I have the same bug. @anchpop did you find any solution?

**Comment by anchpop** [comment]
@zakster12 are you on Android? Running `react-native link` didn't help me

**Comment by zakster12** [comment]
Yes, I tested on Android. On iOS it worked very well from the beginning. Only the Android was a problem but with #143 it works for me

**Comment by elviin** [comment]
I've followed the instructions to set it up on iOS. Flow complains that required modul is not found ('react-native-linear-gradient'), but still i can run the app without any complains (AppleTv).

package.json:

     "dependencies": {
    "apollo-client": "1.x",
    "connected-react-router": "^4.1.0",
    "graphql-tag": "2.x",
    "history": "^4.6.1",
    "moment": "^2.18.1",
    "react": "16.0.0-alpha.6",
    "react-apollo": "1.x",
    "react-native": "0.43.4",
    "react-native-device-detection": "^0.1.3",
    "react-native-linear-gradient": "^2.0.0",
    "react-native-tableview": "^1.7.0",
    "react-redux": "^5.0.3",
    "react-router": "^4.1.1",
    "redux": "^3.6.0"
     },
      "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-jest": "19.0.0",
    "babel-preset-flow": "^6.23.0",
    "babel-preset-react-native": "1.9.1",
    "flow-bin": "^0.47.0",
    "flow-remove-types": "^1.2.1",
    "jest": "19.0.0",
    "react-test-renderer": "15.4.2"
    },




					<LinearGradient colors={['red', 'green', 'blue']} style={{ flex: 1,
        paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 5
      }}>
  						<Text style={{
        fontSize: 70,
    textAlign: 'center',
    margin: 10,
    color: '#ffffff',
    backgroundColor: 'transparent',
      }}>
    						Sign in with Facebook
  						</Text>
					</LinearGradient>

**Comment by anchpop** [comment]
@zakster12 I ran react `react-native link` and it said `linking react-native-linear-gradient` but it still has the same result before and after rebuilding the app :( 

I also tried deleting the `android/app/build` folder but that didn't help either.

**Comment by anchpop** [comment]
I re-ran `npm install react-native-linear-gradient`, then ran `react-native link`, then deleted the folder at `android/app/build`, then ran `react-native run-android` all from an administrator command prompt, and it worked! Thanks everybody!
