### ISSUE TITLE
Add in android/app/build.gradle is producing error

### ISSUE THREAD

**Issue by 0mkara** [react-native-community/react-native-linear-gradient#176]
Adding `compile project(':react-native-linear-gradient')` to `android/app/build.gradle` produces error in `react-native: 0.44.2`
However project compiles successfully without adding it to `android/app/build.gradle`

**Comment by dpkirchner** [comment]
The error is, specifically, `Error:Project :app declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :react-native-linear-gradient.`, FWIW. This may be the same issue as in #159.

**Comment by sibelius** [comment]
link error
