### ISSUE TITLE
react-native-linear-gradient horizontal styling?

### ISSUE THREAD

**Issue by petroa** [react-native-community/react-native-linear-gradient#180]
Hi,

Just wanted to ask if anyone knows if the linear gradient component can be styled so the gradient appears left to right rather than top to bottom?

Appreciate your help.

Cheers.

**Comment by khovansky-al** [comment]
@petroa You could use `start` and `end` props for this. Example:
```
<LinearGradient
  style={styles.gradient}
  colors={['#FFFFFF', '#FF0000']}
  start={{ x: 0, y: 1 }}
  end={{ x: 1, y: 1 }}
/>
```

**Comment by petroa** [comment]
Thanks al. 
Appreciate it.
Cheers.
