### ISSUE TITLE
red box on iphone 4s?

### ISSUE THREAD

**Issue by jcbiznoff** [react-native-community/react-native-linear-gradient#182]
There is red box around the LinearGradient component andI am seeing only on the 4s (9.3). I am using like below. What are the possible reasons?

` .    <LinearGradient
          colors={...}
          style={styles.gradient}
        >
          <View style={styles.container}>
          ....
          </View>
        </LinearGradient>
`

React Native: 0.42
React native linear gradient: 2.0.0

**Comment by Uby501** [comment]
Did you rebuilt the Xcode project, after you added linear-gradient? I had the same issue, I solved it just running `react-native run-ios`so it rebuilt the project.

**Comment by cesargdm** [comment]
Had the same problem on iPad Air 2 Simulator, thanks @ulentini

**Comment by edvaldoszy** [comment]
I am facing the same problem on Android.
I've already rebuilt the project but didn't solve the problem.

**Comment by sibelius** [comment]
link error
