### ISSUE TITLE
LinearGradient as background 

### ISSUE THREAD

**Issue by LitileXueZha** [react-native-community/react-native-linear-gradient#184]
use linear-gradient as background, then i create a brother  View  which is absolute and can't see it even adjust zIndex

**Comment by rdixonbhw** [comment]
Just put components inside the LinearGradient as if it were a view.

```
<LinearGradient>
    <View>
    ...
    </View>
</LinearGradient>
```

**Comment by damathryx** [comment]
using version 2.4.0 but it doesn’t work. the view is behind the gradient

**Comment by tapannathvani** [comment]
How can i set a gradient color as a background color of the app ?

**Comment by sibelius** [comment]
follow this https://github.com/react-native-community/react-native-linear-gradient/issues/184#issuecomment-311176574

**Comment by sdg9** [comment]
A recursive infinite loop 

> follow this [#184 (comment)](https://github.com/react-native-community/react-native-linear-gradient/issues/184#issuecomment-311176574)
