### ISSUE TITLE
Not working on React Native 0.45.1

### ISSUE THREAD

**Issue by nmfzone** [react-native-community/react-native-linear-gradient#185]
I have simple implementation, follow from the example..

**Step to reproduce**
1. `react-native init Project`
2. `yarn add react-native-linear-gradient`
3. `react-native link`

**Code**
```
import React, { Component } from 'react'
import {
  StyleSheet,
  Text,
  View,
} from 'react-native'
import { connect } from 'react-redux'
import LinearGradient from 'react-native-linear-gradient'

class HomeContainer extends Component {
  render = () => (
    <View>
      <Text>Welcome!</Text>

      <LinearGradient colors={['#4c669f', '#3b5998', '#192f6a']} style={styles.linearGradient}>
        <Text style={styles.buttonText}>
          Click me!
        </Text>
      </LinearGradient>
    </View>
  )
}

const styles = StyleSheet.create({
  linearGradient: {
    flex: 1,
    marginTop: 20,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 5
  },
  buttonText: {
    fontSize: 18,
    fontFamily: 'Gill Sans',
    textAlign: 'center',
    margin: 10,
    color: '#000000',
    backgroundColor: 'transparent',
  },
})

const mapStateToProps = (state) => ({
  //
})

export default connect(
  mapStateToProps
)(HomeContainer)
```

but It doesn't work.

**Screenshot**
![Screenshot](https://user-images.githubusercontent.com/10361906/27663125-0bac0b94-5c8b-11e7-89b1-e1d3863bbe00.png)

**Comment by marcodefreitas** [comment]
Had the same issue while running on an iPhone 6 iOS 10.0 target device.
Changed target device and OS and it started working.
This might be a cache problem.

**Comment by nmfzone** [comment]
@marcodefreitas I guess you're right. But I've try to run the app on an iPhone 6 iOS 10.2, iPhone 7 iOS 10.2 and iPhone 7s iOS 10.2 but nothing different..

**Comment by nmfzone** [comment]
Whoops! I found the problem.
The problem comes from `<View />`. It should have `flex` style.
