### ISSUE TITLE
The SDK Build Tools revision is too low

### ISSUE THREAD

**Issue by shayanzoro** [react-native-community/react-native-linear-gradient#187]
When I update my gradle plugin to 2.3.2, build failes:
`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-linear-gradient'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':react-native-linear-gradient'. Minimum required is 25.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
`

**Comment by sibelius** [comment]
use this approach https://github.com/react-native-community/rncamera-example/blob/master/android/build.gradle#L36
