### ISSUE TITLE
remove react-native-linear-gradient

### ISSUE THREAD

**Issue by killinit** [react-native-community/react-native-linear-gradient#189]
impossible to make:
`npm remove react-native-linear-gradient`

and after i still have in settings.gradle

`include ':react-native-linear-gradient'
project(':react-native-linear-gradient').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-linear-gradient/android')`

and
`cd android && ./gradlew assembleRelease`
give build failed 

;-(

I have bypass the problem installing lib once again ( and I am not using it )

**Comment by rh389** [comment]
Try:
```
npm install react-native-linear-gradient
react-native unlink react-native-linear-gradient
npm remove react-native-linear-gradient
```

`react-native unlink` is used to remove iOS and android links to native libraries, but it only works while the package is installed.

**Comment by sibelius** [comment]
link error

**Comment by sirajalam049** [comment]
Hello,
I'm using autolinking. How to unlink when using autoliking?
