### ISSUE TITLE
Error while updating backgroundColor of a view manager by RCTVideo

### ISSUE THREAD

**Issue by zztiswb116** [react-native-community/react-native-linear-gradient#191]
![image](https://user-images.githubusercontent.com/2384360/28147093-bfc700d6-67b0-11e7-8343-987f32cc0579.png)

when i use [https://github.com/react-native-community/react-native-video](url) the react-native-video i meet this error crashed app by android but in ios is ok ! 
android 7.0+  RN version :
"dependencies": {
		"jcore-react-native": "^1.1.3",
		"jpush-react-native": "^1.6.6",
		"koa": "2.0.0",
		"native-base": "^2.1.5",
		"react": "16.0.0-alpha.12",
		"react-native": "0.45.1",
		"react-native-app-intro": "^1.1.5",
		"react-native-device-info": "^0.10.2",
		"react-native-keyboard-aware-scroll-view": "^0.2.9",
		"react-native-root-toast": "^1.1.2",
		"react-native-scrollable-tab-view": "^0.6.7",
		"react-native-splash-screen": "^2.1.0",
		"react-native-vector-icons": "^4.2.0",
		"react-native-video": "^1.0.0",
		"react-native-video-player": "^0.7.0",
		"react-navigation": "^1.0.0-beta.11",
		"underscore": "^1.8.3"
	},
	"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "1.9.2",
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.12"
	},
	"jest": {
		"preset": "react-native"
	}

**Comment by justgeek** [comment]
same issue was reported here:
https://github.com/react-native-community/react-native-video/issues/649

**Comment by radex** [comment]
Hey! I'm closing this since this is a stale issue. If you believe it's still relevant to fix, post a comment and I'll reopen.
