### ISSUE TITLE
no-SSL dependencies

### ISSUE THREAD

**Issue by JSafaiyeh** [react-native-community/react-native-linear-gradient#194]
I have a need for react-native-linear gradient; however, I cannot download dependencies through SSL (company proxy).

Is there a solution to this? 

I have tried changing the jcenter bintray in `node_modules/react-native-linear-gradient/android/build.gradle` to
```java
jcenter {
  url 'http://jcenter.bintray.com'        
}

**Comment by sibelius** [comment]
not a problem with this package
