### ISSUE TITLE
linear-gradient direction from left to right

### ISSUE THREAD

**Issue by yaoyin2014** [react-native-community/react-native-linear-gradient#199]
can't it gradient from left to right?

**Comment by yaronlevi** [comment]
Looking for this as well

**Comment by yaronlevi** [comment]
Can be achieved with this:
https://github.com/react-native-community/react-native-linear-gradient/issues/98

Although I think this should be documented more clearly that this is the way to achieve horizontal gradient.

**Comment by vinothjdx** [comment]
<LinearGradient start={{x: 0, y: 0.75}} end={{x: 1, y: 0.25}} colors={[ '#f74e7f' , '#f74e7f' , '#f74e7f' , '#f87b48', '#f87b48']} style={styles.linearGradient}>
  <Text style={styles.buttonText}>
   this is button
  </Text>
</LinearGradient>

**Comment by radex** [comment]
Hey! I'm closing this since this is a stale issue. If you believe it's still relevant to fix, post a comment and I'll reopen.

**Comment by Bek-Tech** [comment]
start={{ x: -1, y: 0 }}
   end={{ x: 1, y: 0 }}
use this
