### ISSUE TITLE
Error while using with react-native-photo-view

### ISSUE THREAD

**Issue by manpreetmannysingh** [react-native-community/react-native-linear-gradient#204]
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-photo-view:mergeReleaseResources'.
> Error: java.lang.RuntimeException: java.io.EOFException: End of input at line
1 column 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 56.138 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html`

RN : 0.45.1
"react-native-photo-view": "^1.2.0",
"react-native-linear-gradient": "^2.1.0",

Any help ?

**Comment by ekimlinger** [comment]
I think your issue has more to do with react-native-photo-view. I had the same issue and it was because of `react-native link`.

**Comment by sibelius** [comment]
not related to this package
