### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by david-olaf** [react-native-community/react-native-linear-gradient#208]
I followed installation tutorial and run for iOS. And I got this message.

"Cannot read property 'map' of undefined"

Package.js
`"react-native-linear-gradient": "^2.2.0",`

index.ios.js
```
<LinearGradient
            style={{ flex: 1 }}
            start={{ x:0, y:0.8 }}
            end={{ x:0, y:1 }}
            colors={['transparent', Constant.color.background]}
          >
            <Image
              style={{ width:'100%', height:'100%' }}
              source={ imgPreview }
              resizeMode='stretch' />
          </LinearGradient>
```

What is problem?

**Comment by kumarisoni** [comment]
Is the variable 'Constant.color.background' defined before you are using it?

**Comment by camnicklaus** [comment]
I had this issue when I tried to use 'color' instead of 'colors' as a prop but it looks like you have it spelled correctly.

**Comment by radoncreep** [comment]
> I had this issue when I tried to use 'color' instead of 'colors' as a prop but it looks like you have it spelled correctly.

thanks @camnicklaus.. this works use "colors" prop not "color", as it could be assigned a list with more than one color.
