### ISSUE TITLE
undefined is not an object (evaluating 'colors.map')

### ISSUE THREAD

**Issue by kadiraydinli** [react-native-community/react-native-linear-gradient#216]
How can I resolve this error?
![screenshot_2017-09-14-23-41-44](https://user-images.githubusercontent.com/9320037/30456059-ce406c70-99aa-11e7-8055-9fc1d385c4e9.png)
Thanks in advance.

**Comment by ilhamahp** [comment]
I encounter the same problem here

**Comment by turkcekod** [comment]
Unfortunately I could not find it. He makes changes in the application and uses the application. @ilhamahp

**Comment by kadiraydinli** [comment]
Unfortunately I could not find it. He makes changes in the application and uses the application. @ilhamahp

**Comment by kadiraydinli** [comment]
Unfortunately, I could not find it. I made changes in ready-made application. @ilhamahp

**Comment by MarkRatFelt** [comment]
What did you exactly do?

**Comment by trinadhkoya9** [comment]
undefined is not an object (evaluating 'colors.map') #216

**Comment by zoftse** [comment]
Hey have you got any solution for this,, i have too this problem faces

**Comment by vladfridman** [comment]
I had the same problem because in my code I used color attribute instead of colors. Hope it helps someone.

**Comment by mohmdalfaha** [comment]
For me It happens, but I just restarted the Metro Bundler then it worked.

**Comment by andras-gyarmati** [comment]
I tried to use it in Vue Native and got a similar error.

import { LinearGradient } from "expo-linear-gradient";
<linear-gradient colors="{['#4c669f', '#3b5998', '#192f6a']}" style="{styles.linearGradient}"/>

error: 

TypeError: colors.map is not a function. (In 'colors.map(_reactNative.processColor)', 'colors.map' is undefined)

This error is located at:
  in LinearGradient (created by ReactVueComponent)
..

package-lock.json : 

"expo-linear-gradient": "~8.0.0",

"expo-linear-gradient": {
      "version": "8.0.0",
      "resolved": "https://registry.npmjs.org/expo-linear-gradient/-/expo-linear-gradient-8.0.0.tgz",
      "integrity": "sha512-5G3ePGAHUoyBWbGITw5RtdJpssH8TXhCgt55cV+5LTTFjr51OZcuOmGua1vRoVFKBC/9ibLW465GEx9H/HS07Q=="
    },

**Comment by ReisMari** [comment]
I had the same problem and in my case it was just a misspelling, I had written "color" instead of "color**s**".
Check your code for spelling mistakes.

**Comment by akhilrath** [comment]
> For me It happened, but I just restarted the Metro Bundler then it worked

This worked for me. Restarting the metro sever solved the problem

**Comment by VashaMasha** [comment]
In my case the trouble was in "colors" prop of RefreshControl. It was written "colors={'#5533EA'}" instead  "colors={['#5533EA']}"

**Comment by amanjatx** [comment]
If anybody is still getting this error, then please add colors in LinearGradient 
I was doing this `<LinearGradient>`
then I tried this `<LinearGradient colors={['#4c669f', '#3b5998', '#192f6a']}>` and yes it is working now and the error is gone

**Comment by shivam-dev01** [comment]
Same here. Does anybody have any idea to fix this problem?

**Comment by monkeyK1n9** [comment]
> I had the same problem and in my case it was just a misspelling, I had written "color" instead of "color**s**". Check your code for spelling mistakes.

This was my case too, thanks

**Comment by Rahul0001k** [comment]
i was getting this error because in     <LinearGradient colors={''} /> i was sending empty string but this was not a good way.. then i change this to <LinearGradient colors={['red','green']} />... 

:)
