### ISSUE TITLE
react-native-linear-gradient Only red border is visible on iOS

### ISSUE THREAD

**Issue by zhanghuiyun** [react-native-community/react-native-linear-gradient#218]
react-native-linear-gradient Only red border is visible on iOS

**Comment by NickKotowski** [comment]
I had the same problem and saw that you asked this just a few hours ago. I reinstalled the entire package, this time following the manual instructions and now it is working. The following steps are the important ones:

> 1.) Open your project in XCode, right click on Libraries and click Add Files to "Your Project Name" Look under node_modules/react-native-linear-gradient and add BVLinearGradient.xcodeproj. (Screenshot).
2.) Add libBVLinearGradient.a to Build Phases -> Link Binary With Libraries (Screenshot).
3.) Click on BVLinearGradient.xcodeproj in Libraries and go the Build Settings tab. Double click the text to the right of Header Search Paths and verify that it has $(SRCROOT)/../react-native/React - if it isn't, then add it. This is so XCode is able to find the headers that the BVLinearGradient source files are referring to by pointing to the header files installed within the react-native node_modules directory. (Screenshot).

**Comment by zhanghuiyun** [comment]
Thank you. I'll try it now

**Comment by nillo** [comment]
i was able to solve this by doing this

> yarn install react-native-linear-gradient
> react-native link

restart packager.
done.

**Comment by 96506926** [comment]
i try "npm install react-native-linear-gradient  and react-native link" but it's also show me a red border and no aother color @NickKotowski @nillo

**Comment by nazaslater** [comment]
same error as the @zhanghuiyun.

**Comment by zhanghuiyun** [comment]
I've implemented it, and the reason I'm here is because the client side dependency in my project is invalid and needs to be introduced by the client @nazaslater

**Comment by rajatbeck** [comment]
facing the same issue ...tried manual add the dependency ..no success...

**Comment by mattmischuk** [comment]
Also experiencing this issue, tried all of the above steps.

**Comment by RotemShaanan** [comment]
Having the same issue, did anyone find anything to solve it?

**Comment by wellyal** [comment]
#219 duplicated

**Comment by arribbar** [comment]
Fix the issue doing the install manually on iOS. 
I added then `libBVLinearGradient.a` to `Linked Frameworks and Libraries` and it works !

**Comment by wellyal** [comment]
@arribbar thx, worked for me.

**Comment by vilka-vk** [comment]
On Android the same problem

**Comment by vilka-vk** [comment]
Хэй, ребят! Просто переустановите приложение:

Удалите его со своего устройства
Заново запустите сборку в симулятор
Hey, guys! Just reinstall the application:

Uninstall it from your device
Re-run the assembly in the simulator

**Comment by rkhaslarov** [comment]
On Android still the same problem

**Comment by Balamir** [comment]
Just use `react-native link  react-native-linear-gradient` command after install and rebuild.

**Comment by followfire** [comment]
I solved this problem by commond "react-native run-android".Then it works.
My English is poor ,hope u can understand.

**Comment by shuaibird** [comment]
Be sure to recompile the app after installing the library, which literally means running the `react-native run-ios` and `react-native run-android`

**Comment by sibelius** [comment]
link error
