### ISSUE TITLE
Do not works with react-native 0.48.3...

### ISSUE THREAD

**Issue by SkyzohKey** [react-native-community/react-native-linear-gradient#219]
:(

**Comment by jeffpc1993** [comment]
Yes. Does not seem to work.

**Comment by smilledge** [comment]
Specifically whats not working? What's the error?

Maybe check #140, this resolved the errors I had after updating.

**Comment by SkyzohKey** [comment]
No error. Just a blank view instead of the gradient :/

**Comment by oriharel** [comment]
Same here

**Comment by oriharel** [comment]
Found a workaround - you need to eject from the CRNA (create react native app), then
`rnpm link`

**Comment by wellyal** [comment]
Not working for react-native: 0.49.3 either :(

**Comment by oriharel** [comment]
@wellyal iOS or Android?

**Comment by wellyal** [comment]
@oriharel Tried on IOS
![image](https://user-images.githubusercontent.com/3047016/31666621-a873f774-b32b-11e7-8550-f040462b3aed.png)

**Comment by oriharel** [comment]
Did you create a project with create-react-native-app? If so, did you try 'yarn run eject?

**Comment by wellyal** [comment]
I've used react-native init to create the project.

**Comment by wellyal** [comment]
when I add manually the libBVLinearGradient.a in the build phase of IOS it did the trick to me.

**Comment by vilka-vk** [comment]
On Android the same problem

**Comment by oriharel** [comment]
@vilka-vk check MainApplication.java. do you have the class instantiated there?

**Comment by vilka-vk** [comment]
Хэй, ребят! Просто переустановите приложение:
1) Удалите его со своего устройства
2) Заново запустите сборку в симулятор

Hey, guys! Just reinstall the application:
1) Uninstall it from your device
2) Re-run the assembly in the simulator

**Comment by henrikra** [comment]
Just made fresh install with RN 0.48.4. Do everything that is in the README :D This can be closed

**Comment by vilka-vk** [comment]
@henrikra this problem doesn't depend on the version of RN. I have it fresh. The bottom line is that you need to rebuild the application, i.e. remove from the device and run the assembly again.
And the instruction in the README is so-so.

**Comment by henrikra** [comment]
You don't have to remove the app from device. You have to always rebuild the app when using libraries that have native code :P There is nothing special here.

**Comment by rkhaslarov** [comment]
No worked for me RN (0.49), I do everything, even i deleted android folder, its not show up (

**Comment by vilka-vk** [comment]
@rkhaslarov ты пробовал удалить приложение с девайса и запустить сборку заново? Мне это помогло

**Comment by rkhaslarov** [comment]
@vilka-vk Я вообще даже полностью удалял папку андроид и заново все делал толку 0

**Comment by rkhaslarov** [comment]
@vilka-vk причем я вижу что в билде он есть, в списке.

**Comment by rkhaslarov** [comment]
Problem was solved when i came into android dir and run gradlew clean =/

**Comment by sibelius** [comment]
upgrade to latest react-native version
