### ISSUE TITLE
Android gradle buildToolsVersion error

### ISSUE THREAD

**Issue by dominikeinkemmer** [react-native-community/react-native-linear-gradient#221]
Hi,

when I tried to use react-native run-android I get the following error:

![image](https://user-images.githubusercontent.com/18051009/30974753-5da92cca-a4ab-11e7-974c-0f023d04effa.png)

Is it possible to update the build-version in the project to the latest build-version (25.0.2). I changed it in my local project for this npm-module to check if it works and it ran any without issues.

**Comment by henrikra** [comment]
This has nothing to do with this library. This will help you :) https://blog.bam.tech/developper-news/boost-compilation-time-react-native-android-app-latest-android-build-tools

**Comment by steveccable** [comment]
That article is listing a workaround for a library using an old version of the build tools.  While it is a way to get past the problem and allow usage of the library, that doesn't mean it isn't an issue caused by this library...

**Comment by sibelius** [comment]
check this https://github.com/react-native-community/react-native-linear-gradient/issues/233#issuecomment-350694159
