### ISSUE TITLE
Error: "Could not find method compile() for arguments [project ':react-native-linear-gradient']"

### ISSUE THREAD

**Issue by Avivhdr** [react-native-community/react-native-linear-gradient#224]
Added the following line in build.gradle: 
" compile project(':react-native-linear-gradient') ".

Error massage: 
> Could not find method compile() for arguments [project ':react-native-linear-gradient'] on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@4a5905d9.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by Avivhdr** [comment]
Fixed!
There were 2 files named "build.gradle". 
Changed to the other file and it worked.

**Comment by haolipang** [comment]
@Avivhdr , where are the two 'build.gradle' files respectively?
