### ISSUE TITLE
Error in Usage with new version of react native

### ISSUE THREAD

**Issue by Quadriphobs1** [react-native-community/react-native-linear-gradient#230]
Tried to register two views with the same name BVLinearGradient

How can i solve this please

**Comment by boplennon** [comment]
I got the same error with RN 0.50.3

**Comment by reznik789** [comment]
I had the same problem. In my case I returned all android files to state before calling "react-native link" and manually add native files to project like it`s described in README.

**Comment by sibelius** [comment]
related to https://github.com/entria/gol-app/pull/1877

**Comment by sibelius** [comment]
this is happening on RN51 as well

**Comment by sibelius** [comment]
maybe the cause is the same of react-native-svg

check this commit: https://github.com/facebook/react-native/commit/e9780bdc0f00364359f39e5a76a3e43eadb93a4b

and this solution: https://github.com/react-native-community/react-native-svg/pull/486#issuecomment-340111157

**Comment by Unforgiven-wanda** [comment]
Any progress on this error? I'm having the same issue

**Comment by sibelius** [comment]
is this still a problem in master?

can somebody create a PR for this? based on react-native-svg work?

**Comment by sibelius** [comment]
not an error with this package

this could happen when some package defines this package as a dep

like this one https://github.com/tomzaku/react-native-shimmer-placeholder

**Comment by roae** [comment]
I got the same error with RN 0.53.0

**Comment by sibelius** [comment]
we merged this one instead https://github.com/react-native-community/react-native-linear-gradient/commit/9df5291d574b15c569da80b7cc535060ec8d0ac9

can u try using latest master?

**Comment by duro** [comment]
That seems to be working well for me!

**Comment by bithavoc** [comment]
it's fixed in master, can we get a new version in NPM?

**Comment by shohailahm** [comment]
nothing seems to be working

**Comment by shohailahm** [comment]
whats the point of closing issue when it hasn't been fixed??

**Comment by sibelius** [comment]
@shohailahm open another issue with more information and then we can try to help

**Comment by anonrig** [comment]
I'm having the same exact issue when I had an existing react-native-linear-gradient package before I installed @shoutem/ui

<img width="332" alt="screen shot 2018-06-06 at 9 41 02 pm" src="https://user-images.githubusercontent.com/1935246/41058388-54451468-69d2-11e8-8a1d-745b6e6838a3.png">

**Comment by GaneshKonathala007** [comment]
since shoutem is also using the react-native-linear-gradient, metro bundler will go into ambiguity and causes this error. 

you can use shoutems package or remove its dependency as follows.
rm -rf node_modules/@shoutem/ui/node_modules/react-native-linear-gradient

solved my issue
Hope it helps :)

**Comment by thecodecafe** [comment]
@GaneshKonathala007 I used your solution but now I get the following error.
`undefined is not an object (evaluating 'Object.keys(_reactNativeLinearGradient.default.propTypes)')`
Although what really bugs me is why Shoutem is recreating the linear gradient component and forcing it on the user of the library, I use LinearGradient but I didn't use it through Shoutem, they don't even have it in their docs, but it's forced on the user within the library, strange. Just putting it out there though.

**Comment by thecodecafe** [comment]
@GaneshKonathala007 never mind found a fix, so for anyone coming here, I assume you've installed Shoutem UI in your project, simply use the LinearGradient from Shoutem UI instead, it imports react-native-linear-gradient and tries to modify it by adding styles to it, so instead of using.
`import LinearGradient from 'react-native-linear-gradient'`
use
`import {LinearGradient} from '@shoutem/ui';`
hope this helps someone out.

**Comment by pistonsky** [comment]
I solved this by just running `yarn add react-native-linear-gradient` in my repo. I already had that dependency, but I used earlier version, specified with exact version number in my package.json. Another lib was also using react-native-linear-gradient, but newer version, that's why it all ended up having 2 versions of the same lib.
