### ISSUE TITLE
Not working with RN 0.51.0-rc.2

### ISSUE THREAD

**Issue by tiagoalves** [react-native-community/react-native-linear-gradient#240]
While upgrading my app the the currently latest RN release candidate (0.51.0-rc.2), the usage of this module crashes the app but it appears that it's an issue of React Native itself.

Basically, the `start` and `end` properties are not correctly handled by RN. I get this error:

    TypeError: expected dynamic type 'double', but had type 'array'

It seems as if RN is considering that `start` and `end` are `@ReactPropGroup` instead of `@ReactProp`. I've changed this module locally to use the prop name "startsomething" instead of "start" and it worked again.

I've opened an issue in the RN repo itself: facebook/react-native#17030

This is not an issue report but rather an FYI.

**Comment by Kottidev** [comment]
approved 

![image](https://user-images.githubusercontent.com/12915009/33715440-c87d174a-db52-11e7-946b-36b400d4ce30.png)

**Comment by wellyshen** [comment]
I have the same issue

**Comment by pithcou** [comment]
Same error, using RN 0.51
`TypeError: expected dynamic type 'double', but had type 'array'`

**Comment by MichaelDanielTom** [comment]
This is addressed in https://github.com/react-native-community/react-native-linear-gradient/pull/243, so if you guys want a quick fix until the PR is merged, you can fork/depend on the code in @bilalsyed001's branch.

**Comment by sibelius** [comment]
fixed on master
