### ISSUE TITLE
Linear Gradient not working on IOS

### ISSUE THREAD

**Issue by gwesseling** [react-native-community/react-native-linear-gradient#241]
The linear gradient is not woking on IOS. It's only shows one color and it's not even close to the gradient I want. On android it's showing the right colors.

react: 16.0.0
react-native: 0.50.4
react-native-linear-gradient: ^2.3.0

IOS:
![ios](https://user-images.githubusercontent.com/12099455/33554917-d665cb78-d8fe-11e7-93a7-ea9022914b9e.png)

Android:
![android](https://user-images.githubusercontent.com/12099455/33554931-e35071c6-d8fe-11e7-8ec2-7e229fdea397.png)

Kind regards,

gwesseling

**Comment by muresanandrei** [comment]
@gwesseling For me it works on ios but on Android I get Native component for BVLinearGradient does not exist. I've done  react-native link also manually added on android how it says. How did you make it work on Android?

**Comment by gwesseling** [comment]
@muresanandrei I used react-native link for linking the gradient. You could try to unlink it an relink it to Android (react-native unlink "package-name"). Or you could try to reinstall the package. On Android it works for me every single time. but it doesn't seem to work for me on IOS.

**Comment by muresanandrei** [comment]
@gwesseling Can you give me your gradient code to check on my side see if I can help you since it works on ios on my side.

**Comment by gwesseling** [comment]
yeah sure, here's the code I'm using for the background.

'
import React, { Component } from 'react';
import { View, Text, Image, Dimensions } from 'react-native';
import LinearGradient from 'react-native-linear-gradient';

class Splash extends Component {

    render() {
        return(
            <View style={ styles.container }>
                <LinearGradient
                    style={ styles.linearGradient }
                    colors={['#F99F01', '#DB3069']}
                    locations={[0,5]}
                    start={{x: 0.0, y: 0}}
                    end={{x: 0.5, y: 1.0}}
                />
                <LinearGradient
                    style={ [styles.arch, { right: Dimensions.get('window').width / 2}] }
                    colors={['#F5900E', '#DC3565']}
                    locations={[0,5]}
                    start={{x: 0.0, y: 0}}
                    end={{x: 0.5, y: 1.0}}
                />
                <LinearGradient
                    style={ [styles.arch, { left: Dimensions.get('window').width / 2}] }
                    colors={['#F07F1E', '#DB3069']}
                    locations={[0,5]}
                    start={{x: 0.0, y: 0}}
                    end={{x: 0.5, y: 1.0}}
                />
            </View>
        );
    }
}

const styles = {
    container: {
        flex: 1
    }
    arch: {
        height: Dimensions.get('window').height - 230,
        width: Dimensions.get('window').width / 2 + 25,
        position: 'absolute',
        top: 230,
        opacity: 0.5,
        borderTopLeftRadius: 100,
        borderTopRightRadius: 100
    },
    linearGradient: {
        flex: 1,
    },
};

export default Splash;
`

**Comment by gwesseling** [comment]
Found the reason why it looks so different on IOS. Location is working differently on IOS. After removing the location prop my gradient is showing more colors. Location should not be higher than 1.

**Comment by gwesseling** [comment]
Can someone close this issue. I found my mistake and it has been fixed. Thanks!

**Comment by pooja-wal** [comment]
Hey @gwesseling , can you let me know how you fixed it? I am facing the same issue.

**Comment by Dev2927** [comment]
<LinearGradient
              colors={[theme.PRIMARY, theme.MID]}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 0 }}
              style={styles.cardHeader}>
              <View style={styles.headerDot} />
              <Text style={styles.heading} numberOfLines={2}>
                {item?.heading}
              </Text>
            </LinearGradient>


Still mine is not working in IOS! Anyone know why ????
