### ISSUE TITLE
Android Issue linking package

### ISSUE THREAD

**Issue by SameenaK** [react-native-community/react-native-linear-gradient#245]
Hi all,

When I attempt to link my project to this package with Android, I run into some issues. When I follow all the manual linking instructions, my build fails and I get the following error from my MainApplication.java file: `error: method does not override or implement a method from a supertype @Override`

I realized that override is deprecated, and tried to remove `@Override` from this file. When I do this, my build succeeds but instead of a gradient, I see red borders only. I read that this means that maybe the package wasn't linked successfully, but I don't know how to fix it if override is deprecated.

I would love to hear any advice. Thank you!

**Comment by sibelius** [comment]
is this issue still happening on master?

**Comment by SameenaK** [comment]
I just went through the set-up steps again, and this time I am getting this error:

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.`

Any ideas on how to solve it?

**Comment by sibelius** [comment]
link error
