### ISSUE TITLE
gradient direction from bottom to top?

### ISSUE THREAD

**Issue by NamanAulakh** [react-native-community/react-native-linear-gradient#248]
If I add the following code:

```
<LinearGradient
          colors={['rgba(0,0,0,.5)', 'transparent']}
          style={{
            position: 'absolute',
            left: 0,
            right: 0,
            bottom: 0,
            height: 85,
            zIndex: 1,
          }}
        />
```

I get a gradient which is dense at the top and it's density reduces downwards:

![screen shot 2017-12-19 at 2 08 31 pm](https://user-images.githubusercontent.com/11032725/34148136-26fa816e-e4c6-11e7-9411-f0ad4b54ea80.png)

Is there a way to reverse the density, I mean density should be max at the bottom and min at the top?

P.S.: I tried changing `start` and `end` props but since I'm unable to understand it, It doesn't work.

**Comment by jstheoriginal** [comment]
i think you just need to reverse your colours. it will use them by default from top to bottom. so if you want the top to be transparent and bottom to have the colour, then switch them.

**Comment by NamanAulakh** [comment]
@jstheoriginal yes, it worked.
Thanks.
