### ISSUE TITLE
Undefined is not an object (PropTypes.oneOfType)

### ISSUE THREAD

**Issue by hamidhadi** [react-native-community/react-native-linear-gradient#249]
I have `prop-types` in my project but I get this error!

react-native: 0.51.0,
react-native-linear-gradient: ^2.3.0

<img width="373" alt="screen shot 1396-09-30 at 13 18 39" src="https://user-images.githubusercontent.com/6258297/34250349-d7f0c424-e651-11e7-9609-4a48b0a64e2d.png">

**Comment by sibelius** [comment]
fixed on master
