### ISSUE TITLE
startPoint, endPoint is not working

### ISSUE THREAD

**Issue by jeetblswami** [react-native-community/react-native-linear-gradient#250]
startPoint and endPoint have no effect on the gradient.

I am on 2.4.0

**Comment by Lube** [comment]
Can confirm

**Comment by dluksza** [comment]
Here the same!

**Comment by dluksza** [comment]
I've figured this out! In 2.4.0 only internal API properties were changed to `startPoint` and `endPoint`. Public component API was not changed, it is still called `start` and `end`.

I had patched locally `react-native-linear-gradient` and used `startPoint` and `endPoint` properties in their's public API. After changing this back to `start` and `end` everything worked fine again!

**Comment by Lube** [comment]
Pull request [#252](https://github.com/react-native-community/react-native-linear-gradient/pull/252) submitted, if you can please try the fix with this 

```
    "react-native-linear-gradient": "git+https://github.com/Lube/react-native-linear-gradient",
```

**Comment by hqro** [comment]
@Lube Thanks, it works for me !

**Comment by jeetblswami** [comment]
start and end are working normally.
closing.
