### ISSUE TITLE
Gradient Color as Background of the App 

### ISSUE THREAD

**Issue by tapannathvani** [react-native-community/react-native-linear-gradient#257]
How can i set the linear gradient color as the background color of the app ? I checked the examples but its all related to a button or textinput.. And its all in render (). how can i do the same thing in StyleSheet ?

**Comment by sdg9** [comment]
#184 doesn't completely answer your question but may help.

**Comment by sibelius** [comment]
follow this https://github.com/react-native-community/react-native-linear-gradient/issues/184#issuecomment-311176574
