### ISSUE TITLE
Changes needed for gradle 3.0.1 compatibility

### ISSUE THREAD

**Issue by pacamara** [react-native-community/react-native-linear-gradient#258]
Some minor changes are needed for gradle 3.0.1 compatibility: in android/build.gradle:
* Remove the `buildToolsVersion`, gradle now specifies a default and the current value conflicts with that.
* Change `provided` to `compileOnly`.

We are currently hacking these changes with a script in status.im, and would rather it is fixed upstream. Thanks!

Parent issue: https://github.com/status-im/status-react/issues/3037

**Comment by sibelius** [comment]
use this approach https://github.com/react-native-community/react-native-camera/blob/master/Example/android/build.gradle#L28
