### ISSUE TITLE
ios Error: Invariant Violation: Native component for "BVLinearGradient" does not exist

### ISSUE THREAD

**Issue by alainib** [react-native-community/react-native-linear-gradient#263]
on Android it work but on iOs i have the following error 
Error: Invariant Violation: Native component for "BVLinearGradient" does not exist

i installed the last version and use `react-native link` , clean code from Xcode and rebuild it but the error didn't go 

![capture d ecran 2018-02-05 a 16 42 35 1](https://user-images.githubusercontent.com/7910081/35813488-068cd488-0a94-11e8-9474-e8db2bb88cba.png)

i tryed manually install 
under Libraries i dont have a folder with my project name

**Comment by gabberr** [comment]
So on the left, click on the top - your project - and then select 'Build Phases' tab.

Add libBVLinearGradient.a to Build Phases -> 'Link Binary With Libraries' list. 

You can either select it with plus or drag it in from the left (expand Libraries, expand BVLinearGradient.xcodeproj, then drag libBVLinearGradient.a to the previously mentioned 'Link Binary With Libraries' list)

Rebuild the project.

**Comment by sibelius** [comment]
link issue
