### ISSUE TITLE
How to use linear gradient with "-180deg" ?

### ISSUE THREAD

**Issue by Johnba1988** [react-native-community/react-native-linear-gradient#264]
I want to do this line `linear-gradient(-180deg, #9F9F9F 0%, #2E2E2E 100%, #000000 100%)` with `react-native-linear-gradient`. Please is it possible ?

**Comment by wswoodruff** [comment]
You can rotate the container holding the gradient, that's the only way I could figure it out when I tried this

**Comment by kilaniba** [comment]
Can you explain me more by code example ?

**Comment by kilaniba** [comment]
Sorry , I don't understand how to do exactly , can you explain me more please ?

**Comment by kikoseijo** [comment]
Any conversion tool from sketch to here?
as `linear-gradient(-180deg, #9F9F9F 0%, #2E2E2E 100%, #000000 100%)`
comes from web and sketch,

Any advices around here? will be much appreciated.

**Comment by Johnba1988** [comment]
@kikoseijo  Thank youuu very much, this what I need , please what I must to change in this code to get the second color image.

**Comment by kikoseijo** [comment]
@Johnba1988 I got it out of the exported SVG, x1, Y1 = start, and X2, Y2 = end.

**PRO TIP:**
Top left = 0,0
Bottom right = 1,1

**Comment by Johnba1988** [comment]
@kikoseijo Awesome , Than you very much  .

**Comment by Johnba1988** [comment]
@kikoseijo I can use 3 colors ?

**Comment by kikoseijo** [comment]
Offcourse, you just have to add extra lines for locations + colours.

```xml
<LinearGradient
          start={{ x: 0, y: 0 }}
          end={{ x: 0.5, y: 1 }}
          locations={[0.0, 0.35, 0.99]}
          colors={[
            Colors.getLighten(itemColor, 0.1),
            itemColor,
            Colors.getDarken(itemColor, 0.2)
          ]}>
```

The Color.getDarker its a function I use to dynamic change the color on the theme.

**Comment by Johnba1988** [comment]
@kikoseijo Thank you very very very much :)

**Comment by saikrishna407** [comment]
@kikoseijo  I am woking the simulator. Linear Gradient is perfectly working the Android but IOS is not working Properly 
![screen shot 2018-10-10 at 12 49 27 am](https://user-images.githubusercontent.com/43198184/46721186-42203d00-cc27-11e8-975f-0a2570a455e1.png)
![screen shot 2018-10-10 at 12 54 57 am](https://user-images.githubusercontent.com/43198184/46721193-44829700-cc27-11e8-8f4b-8ab0dae52145.png)
![screen shot 2018-10-10 at 1 23 42 pm](https://user-images.githubusercontent.com/43198184/46721250-67ad4680-cc27-11e8-885a-0b8e659f9f78.png)

![screen shot 2018-10-10 at 1 23 42 pm](https://user-images.githubusercontent.com/43198184/46721236-58c69400-cc27-11e8-9f77-1c9c132e3286.png)
Below one Android And Both Top Images are If I am writing the Text inside the Linear Gradient in Ios the Text has Override.  
without writing Text it's Perfectly Working. Could Please Solve This problem.
Thakingyou

**Comment by kikoseijo** [comment]
@saikrishna407 im not a maintainer of this library at all, sorry, 🤪

**Comment by saikrishna407** [comment]
@kikoseijo  ok Thank you For reply ...

**Comment by radex** [comment]
Hey! I'm closing this since it's a duplicate.
