### ISSUE TITLE
'View' has no propTypes defined

### ISSUE THREAD

**Issue by KrisanuWeavers** [react-native-community/react-native-linear-gradient#266]
React Native Version : 0.53
react-native-linear-gradient : 2.4.0 also tested with 2.3.0

![screenshot_error](https://user-images.githubusercontent.com/25531085/36384546-ab00ca20-15b5-11e8-9577-0b229816a133.png)

**Comment by radex** [comment]
Hey! I'm closing this since this is a stale issue. If you believe it's still relevant to fix, post a comment and I'll reopen.
