### ISSUE TITLE
TypeError: In this environment the sources for assign MUST be an object

### ISSUE THREAD

**Issue by ethanyuwang** [react-native-community/react-native-linear-gradient#273]
I encountered this error when using `react-native-linear-gradient` with "react": "16.3.1", "react-native": "0.55.2", 

![simulator screen shot - iphone 6 - 2018-04-10 at 10 50 19](https://user-images.githubusercontent.com/17556945/38574240-2de9b604-3cad-11e8-9f4d-b19204cb8e36.png)

**Comment by mfsanchez** [comment]
I have the same error, how can i fix that?

**Comment by vdanylov** [comment]
Same issue(

**Comment by ChaoTzuJung** [comment]
Same issue(

**Comment by icemancast** [comment]
Save issue. @ethanyuwang what was the fix?

**Comment by acollazomayer** [comment]
@ethanyuwang same issue

**Comment by Cicko** [comment]
:(

**Comment by matheushf** [comment]
Same here, using Expo App
