### ISSUE TITLE
Doesn't work with latest version of react native

### ISSUE THREAD

**Issue by SergiOnGit** [react-native-community/react-native-linear-gradient#276]

**Comment by SergiOnGit** [comment]
I have used react-native link option and my whole app build failed. Then i removed each line of code which this plugin add in my files and build has succeed

**Comment by sibelius** [comment]
without errors we can't help

**Comment by SergiOnGit** [comment]
This is error

`D:\projects\fortuna\android\app\src\main\java\com\fortuna\MainApplication.java:8: error: cannot find symbol
import com.BV.LinearGradient.LinearGradientPackage;
                            ^
  symbol:   class LinearGradientPackage
  location: package com.BV.LinearGradient
D:\projects\fortuna\android\app\src\main\java\com\fortuna\MainApplication.java:31: error: cannot find symbol
            new LinearGradientPackage()
                ^
  symbol: class LinearGradientPackage
2 errors
Incremental compilation of 1 classes completed in 1.142 secs.
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.`

**Comment by sibelius** [comment]
there is an error in your link

check docs

**Comment by SergiOnGit** [comment]
Which link?What did i do wrong?

if you mean this link: D:\projects\fortuna\android\app\src\main\java\com\fortuna\MainApplication.java it is correct. So can you help?
