### ISSUE TITLE
Props start and end conflicts with react-native Layout Props

### ISSUE THREAD

**Issue by brunolemos** [react-native-community/react-native-linear-gradient#279]
React Native supports the `start` and `end` properties, e.g. `<View start={1} />`. This repo overrides them. This causes typing issues. 

The ideal solution would be that `react-native-linear-gradient` make a new release renaming these props to something else. We could make it backward compatible. Thoughts?

I made this pull request: #280

**Comment by dakooj** [comment]
This type issue has been open for 2 months. Any chance a release with a fix for this will be pushed?

**Comment by brunolemos** [comment]
Not necessary anymore since https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28217 was merged today.
Update `@types/react-native` to v0.56.10+.
