### ISSUE TITLE
No resource found that matches the given name (at 'theme' with value '@style/ImageTranslucentTheme').

### ISSUE THREAD

**Issue by afresh** [react-native-community/react-native-linear-gradient#282]
> PS D:\rnprojects\getart_insititute_rn> react-native run-android
> Scanning folders for symlinks in D:\rnprojects\getart_insititute_rn\node_modules (46ms)
> Starting JS server...
> Building and installing the app on the device (cd android && gradlew.bat installDebug)...
> Observed package id 'build-tools;26.0.0-rc2' in inconsistent location 'D:\android-sdk-windows\build-tools\26.0.0-preview' (Expected 'D:\android-sdk-windows\build-tools\26.0.0-rc2')
> Observed package id 'build-tools;28.0.0-rc1' in inconsistent location 'D:\android-sdk-windows\build-tools\28.0.0-preview' (Expected 'D:\android-sdk-windows\build-tools\28.0.0-rc1')
> Observed package id 'build-tools;26.0.0-rc2' in inconsistent location 'D:\android-sdk-windows\build-tools\26.0.0-preview' (Expected 'D:\android-sdk-windows\build-tools\26.0.0-rc2')
> Observed package id 'build-tools;28.0.0-rc1' in inconsistent location 'D:\android-sdk-windows\build-tools\28.0.0-preview' (Expected 'D:\android-sdk-windows\build-tools\28.0.0-rc1')
> Incremental java compilation is an incubating feature.
> :app:preBuild UP-TO-DATE
> :app:preDebugBuild UP-TO-DATE
> :app:checkDebugManifest
> :app:preReleaseBuild UP-TO-DATE
> :react-native-linear-gradient:preBuild UP-TO-DATE
> :react-native-linear-gradient:preReleaseBuild UP-TO-DATE
> :react-native-linear-gradient:checkReleaseManifest
> :react-native-linear-gradient:preDebugAndroidTestBuild UP-TO-DATE
> :react-native-linear-gradient:preDebugBuild UP-TO-DATE
> :react-native-linear-gradient:preDebugUnitTestBuild UP-TO-DATE
> :react-native-linear-gradient:preReleaseUnitTestBuild UP-TO-DATE
> :react-native-linear-gradient:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
> :react-native-linear-gradient:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
> :react-native-linear-gradient:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library UP-TO-DATE
> :react-native-linear-gradient:prepareComFacebookFrescoDrawee130Library UP-TO-DATE
> :react-native-linear-gradient:prepareComFacebookFrescoFbcore130Library UP-TO-DATE
> :react-native-linear-gradient:prepareComFacebookFrescoFresco130Library UP-TO-DATE
> :react-native-linear-gradient:prepareComFacebookFrescoImagepipeline130Library UP-TO-DATE
> :react-native-linear-gradient:prepareComFacebookFrescoImagepipelineBase130Library UP-TO-DATE
> :react-native-linear-gradient:prepareComFacebookFrescoImagepipelineOkhttp3130Library UP-TO-DATE
> :react-native-linear-gradient:prepareComFacebookReactReactNative0553Library UP-TO-DATE
> :react-native-linear-gradient:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
> :react-native-linear-gradient:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
> :react-native-linear-gradient:prepareReleaseDependencies
> :react-native-linear-gradient:compileReleaseAidl UP-TO-DATE
> :react-native-linear-gradient:compileReleaseNdk UP-TO-DATE
> :react-native-linear-gradient:compileLint UP-TO-DATE
> :react-native-linear-gradient:copyReleaseLint UP-TO-DATE
> :react-native-linear-gradient:compileReleaseRenderscript UP-TO-DATE
> :react-native-linear-gradient:generateReleaseBuildConfig UP-TO-DATE
> :react-native-linear-gradient:generateReleaseResValues UP-TO-DATE
> :react-native-linear-gradient:generateReleaseResources UP-TO-DATE
> :react-native-linear-gradient:packageReleaseResources UP-TO-DATE
> :react-native-linear-gradient:processReleaseManifest UP-TO-DATE
> :react-native-linear-gradient:processReleaseResources UP-TO-DATE
> :react-native-linear-gradient:generateReleaseSources UP-TO-DATE
> :react-native-linear-gradient:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
> :react-native-linear-gradient:compileReleaseJavaWithJavac UP-TO-DATE
> :react-native-linear-gradient:extractReleaseAnnotations UP-TO-DATE
> :react-native-linear-gradient:mergeReleaseShaders UP-TO-DATE
> :react-native-linear-gradient:compileReleaseShaders UP-TO-DATE
> :react-native-linear-gradient:generateReleaseAssets UP-TO-DATE
> :react-native-linear-gradient:mergeReleaseAssets UP-TO-DATE
> :react-native-linear-gradient:mergeReleaseProguardFiles UP-TO-DATE
> :react-native-linear-gradient:packageReleaseRenderscript UP-TO-DATE
> :react-native-linear-gradient:processReleaseJavaRes UP-TO-DATE
> :react-native-linear-gradient:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
> :react-native-linear-gradient:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
> :react-native-linear-gradient:mergeReleaseJniLibFolders UP-TO-DATE
> :react-native-linear-gradient:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
> :react-native-linear-gradient:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
> :react-native-linear-gradient:bundleRelease UP-TO-DATE
> :app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
> :app:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
> :app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library UP-TO-DATE
> :app:prepareComFacebookFrescoDrawee130Library UP-TO-DATE
> :app:prepareComFacebookFrescoFbcore130Library UP-TO-DATE
> :app:prepareComFacebookFrescoFresco130Library UP-TO-DATE
> :app:prepareComFacebookFrescoImagepipeline130Library UP-TO-DATE
> :app:prepareComFacebookFrescoImagepipelineBase130Library UP-TO-DATE
> :app:prepareComFacebookFrescoImagepipelineOkhttp3130Library UP-TO-DATE
> :app:prepareComFacebookReactReactNative0553Library UP-TO-DATE
> :app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
> :app:prepareGetart_insititute_rnReactNativeLinearGradientUnspecifiedLibrary UP-TO-DATE
> :app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
> :app:prepareDebugDependencies
> :app:compileDebugAidl UP-TO-DATE
> :app:compileDebugRenderscript UP-TO-DATE
> :app:generateDebugBuildConfig UP-TO-DATE
> :app:mergeDebugShaders UP-TO-DATE
> :app:compileDebugShaders UP-TO-DATE
> :app:generateDebugAssets UP-TO-DATE
> :app:mergeDebugAssets UP-TO-DATE
> :app:generateDebugResValues UP-TO-DATE
> :app:generateDebugResources UP-TO-DATE
> :app:mergeDebugResources UP-TO-DATE
> :app:bundleDebugJsAndAssets SKIPPED
> :app:processDebugManifest UP-TO-DATE
> :app:processDebugResources
> D:\rnprojects\getart_insititute_rn\android\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:28:28-56: AAPT: No resource found that matches the given name (at 'theme' with value '@style/ImageTranslucentTheme').
> 
> D:\rnprojects\getart_insititute_rn\android\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:24: error: Error: No resource found that matches the given name (at 'theme' with value '@style/ImageTranslucentTheme').
> 
> 
> :app:processDebugResources FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processDebugResources'.
> > com.android.ide.common.process.ProcessException: Failed to execute aapt
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 16.197 secs
> Could not install the app on the device, read the error above for details.
> Make sure you have an Android emulator running or a device connected and have
> set up your Android development environment:
> https://facebook.github.io/react-native/docs/getting-started.html

How to solve this problem?

**Comment by radex** [comment]
Hey! I'm closing this since this is a stale issue. If you believe it's still relevant to fix, post a comment and I'll reopen.
