### ISSUE TITLE
Check the render method of `CellRenderer`.

### ISSUE THREAD

**Issue by xman1979** [react-native-community/react-native-linear-gradient#284]
[tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `CellRenderer`.

This error is located at:
    in BVLinearGradient (at index.ios.js:72)
    in LinearGradient (at AppIntroScreen.js:58)
    in RCTView (at View.js:60)
    in View (at VirtualizedList.js:1664)
    in CellRenderer (at VirtualizedList.js:670)
    in RCTScrollContentView (at ScrollView.js:791)
    in RCTScrollView (at ScrollView.js:887)
    in ScrollView (at VirtualizedList.js:1024)
    in VirtualizedList (at FlatList.js:644)
    in FlatList (at AppIntroSlider.js:152)
    in RCTView (at View.js:60)
    in View (at AppIntroSlider.js:151)
    in AppIntroSlider (at AppIntroScreen.js:78)
    in AppIntroScreen (at SceneView.js:17)
    in SceneView (at SwitchView.js:18)
    in SwitchContainer (at withCachedChildNavigation.js:69)
    in withCachedChildNavigation(SwitchContainer) (at SwitchNavigator.js:11)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at index.js:11)
    in Provider (at index.js:10)
    in EasilyPC (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)

**Comment by radex** [comment]
Hey! I'm closing this since this is a stale issue. If you believe it's still relevant to fix, post a comment and I'll reopen.

**Comment by kkuruva-rpx** [comment]
Hi Guys, 

Facing similar issue  

here 's my package.json 
  },
  "dependencies": {
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.3",
    "react-native-app-intro-slider": "^1.0.1",
    "react-native-elements": "^0.19.1",
    "react-native-ionicons": "^4.4.6",
    "react-native-linear-gradient": "^2.4.2",
    "react-native-vector-icons": "^6.0.2"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.1",
    "react-test-renderer": "16.6.0-alpha.8af6728"
  },
  "jest": {
    "preset": "react-native"


And here's the error. 

Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `CellRenderer`.

This error is located at:
    in BVLinearGradient (at react-native-linear-gradient/index.ios.js:81)
    in LinearGradient (at App.js:58)
    in RCTView (at View.js:44)
    in CellRenderer (at VirtualizedList.js:687)
    in RCTScrollContentView (at ScrollView.js:852)
    in RCTScrollView (at ScrollView.js:977)
    in ScrollView (at VirtualizedList.js:1062)
    in VirtualizedList (at FlatList.js:663)
    in FlatList (at AppIntroSlider.js:178)
    in RCTView (at View.js:44)
    in AppIntroSlider (at App.js:78)
    in div (at App.js:77)
    in App (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)


Thanks for your help in advance.

**Comment by kumarutsav111** [comment]
Kindly fix this. I am beginner and facing same error. please explain

**Comment by hasnainalimj** [comment]
I'm facing same issue kindly reopen and fix it.

**Comment by Mahdouch17** [comment]
Hi everyone, me too i am facing the same issue , please i need your help

**Comment by kumarutsav111** [comment]
this can be the cause of issue:
1: you are passing a data to a string which is undefined. 
2: export from class. import as 
import (abc, xyz } from 'react-native-abd'

**Comment by saabaaah** [comment]
I had the same problem.

Solved it by going from :

`import {MyClass} from './MyFile'
`
into 

`import MyClass from './MyFile'
`
since in 'MyFile' I am using 

`export default MyClass`

Thanks to @kumarutsav111

**Comment by kumarutsav111** [comment]
> I had the same problem.
> 
> Solved it by going from :
> 
> `import {MyClass} from './MyFile' `
> into
> 
> `import MyClass from './MyFile' `
> since in 'MyFile' I am using
> 
> `export default MyClass`
> 
> Thanks to @kumarutsav111

You are welcome. I'm happy to help u 😊

**Comment by clifford-andrew-stevenson** [comment]
I'm having this problem

**Comment by mmkhmk** [comment]
Hi I'm facing this issue.

**Comment by Harshit-1906** [comment]
from this also it was not working

**Comment by Tanererkan06** [comment]
still issue is going on..
