### ISSUE TITLE
Radial gradient?

### ISSUE THREAD

**Issue by niftylettuce** [react-native-community/react-native-linear-gradient#29]

**Comment by nickhudkins** [comment]
@brentvatne wanna support radial gradients?

**Comment by nickhudkins** [comment]
@brentvatne that is... would you like to rename this project react-native-gradient?

**Comment by brentvatne** [comment]
Could do that @nickhudkins. No plan to build this in any time soon but open to contributions

**Comment by dgladkov** [comment]
Same as with #56, this is something that is much easier done on Android than iOS. Right now we use `CAGradientLayer` on iOS which supports linear gradients only, drawing radial gradients requires using `CALayer` directly. [[1]](http://stackoverflow.com/questions/26907352/how-to-draw-radial-gradients-in-a-calayer)

As with #56, I would be happy to contribute Android version if someone implements it on iOS, but I don't think it's a good idea to implement major Android-only features

**Comment by petersuwara** [comment]
We could definitely do with some custom react-native component or style to do radial gradients.
Our only option so far is to go with the following custom native code :
`class CARadialGradientLayer: CALayer {
    
    var center:CGPoint!
    var radius:CGFloat!
    var colors:[CGColor]!
    
    override init(){
        
        super.init()
        
        needsDisplayOnBoundsChange = true
    }
    
    init(center:CGPoint,radius:CGFloat,colors:[CGColor]){
        
        self.center = center
        self.radius = radius
        self.colors = colors
        
        super.init()
        
        needsDisplayOnBoundsChange = true
    }
    
    required init(coder aDecoder: NSCoder) {
        
        super.init()
        
    }
    
    override func draw(in ctx: CGContext) {
        
        ctx.saveGState()
        
        let colorSpace = CGColorSpaceCreateDeviceRGB()
        
        let locations:[CGFloat] = [0.0, 0.9]
        let gradient = CGGradient(colorsSpace: colorSpace, colors: colors as CFArray, locations: locations)
        
//        let startPoint = CGPoint(x: 0, y: self.bounds.height)
//        let endPoint = CGPoint(x: self.bounds.width, y: self.bounds.height)
        
        ctx.drawRadialGradient(gradient!, startCenter: center, startRadius: 0.0, endCenter: center, endRadius: radius, options: CGGradientDrawingOptions(rawValue: 0))
    }
}
`

**Comment by dk0r** [comment]
Would love to see android/iOS support for radial gradients!

**Comment by radex** [comment]
I'm closing this. radial gradients would be great, but since this is a community-driven project, you have to volunteer an implementation in a pull request :)

**Comment by guopeng1994** [comment]
oh my god... still nobody do this...

**Comment by shaundon** [comment]
@guopeng1994 why don't you contribute it?

**Comment by Egizas** [comment]
would be nice to have this

**Comment by TheEhsanSarshar** [comment]
use` react-native-svg` instead
