### ISSUE TITLE
BVLinearGradient does not exist

### ISSUE THREAD

**Issue by kgsachinthaudara** [react-native-community/react-native-linear-gradient#299]
Hi, 

I installed the library from npm and, then properly linked to the native realm. but when I try to use LinearGradient in my application it just generates BVLinearGradient does not exist error. I closed the server and again tried as well as restart the computer, but same as error

**Comment by mattInnov** [comment]
I've got the exact same error even though i also linked it properly and rebuilt it...

**Comment by sibelius** [comment]
make sure you linked properly

**Comment by mattInnov** [comment]
I did, I updated my react-native-cli, then ran react-native link and checked that all 3 steps to link for android had been done, and they were, but the issue remained.... Is there like a cache to clean maybe ?

**Comment by ovaisali08** [comment]
Same Problem.. 
![image](https://user-images.githubusercontent.com/43641800/46144625-f5c41d00-c276-11e8-9b2a-fe34b2feb280.png)
