### ISSUE TITLE
Unknown type name 'UIColor'

### ISSUE THREAD

**Issue by St1ggy** [react-native-community/react-native-linear-gradient#301]
![image](https://user-images.githubusercontent.com/13361661/41646477-1ce6c0b2-749e-11e8-8d95-134e989e0082.png)

https://github.com/react-native-community/react-native-linear-gradient/blob/master/BVLinearGradient/BVLinearGradientLayer.h
Probably missed `#import <UIKit/UIKit.h>` in file above.
I have fixed it locally, but it breaks my pipeline.

**Comment by radex** [comment]
I believe this was fixed. let me know if this is still a problem, and I'll reopen
