### ISSUE TITLE
Example app has no gradient with react-native 0.56.0-rc.4 (observed on iOS) (has screenshot & example)

### ISSUE THREAD

**Issue by CrazyPython** [react-native-community/react-native-linear-gradient#316]
#### Screenshot

![](https://user-images.githubusercontent.com/2363105/42119294-5f14260a-7bd8-11e8-8fac-bd407a83de27.png)

Note the bar of start color at the left, and also the obvious lack of gradient 😜 
#### Demo
```
git clone https://github.com/crazypython/react-native-linear-gradient.git
cd react-native-linear-gradient/Examples/AnimatedGradient
yarn
react-native run-ios
```
The fork has modified these files
- `Examples/AnimatedGradient/package.json` so that
  - yarn installs RNLG from master (to avoid facebook/metro#68)
  - react-native is updated to use 0.56.0-rc.4, and its peerDependencies are corrected
- `Examples/AnimatedGradient/src/index.js` so that it doesn't use the removed `React.createClass` API
- `Examples/AnimatedGradient/yarn.lock` to ensure the dependencies installed on your side deterministically

#### Additional Details
I observed this on-device on my own app as well. I don't know if this issue is present on Android.

**Comment by CrazyPython** [comment]
@k0nserv

**Comment by k0nserv** [comment]
Hey @CrazyPython this regressed with a change I mad but should be working on master after the merge of #315

**Comment by CrazyPython** [comment]
@k0nserv Thanks, it works now.
