### ISSUE TITLE
Warning: Unexpected pop

### ISSUE THREAD

**Issue by pabloga265** [react-native-community/react-native-linear-gradient#318]
Creating this node generates some errors like: "Warning: Unexpected Fiber popped." 
Followed by an infinite stream of errors "Warning: Unexpected pop" on rn-debugger.

No more info provided
```
 <LinearGradient style={styles.switchLinearGradient} colors={['#FFFFFF', '#FFFFFF']}>
    <Text style={{backgroundColor: 'transparent'}}>
        'DOCKS'
    </Text>
</LinearGradient>
```

 "react": "16.3.1",
 "react-native": "0.56.0-rc.4",
 "react-native-linear-gradient": "^2.4.0",

IOs emulator Iphone 6 and 6+, Works fine in android.

**Comment by pabloga265** [comment]
@rahmanmarija No, sorry sadly I was in a bit of a hurry and it was easier to adjust the designs than to fix the issue. :<

**Comment by jaygould** [comment]
I ended up unlinking and re-linking the package using react-native unlink react-native-linear-gradient and that sorted it.

**Comment by dsouzaedison** [comment]
Had the same issue. Manual linking on Xcode solved the problem.

**Comment by radex** [comment]
Hey! I'm closing this since it looks like a solved issue.

**Comment by laurent22** [comment]
I'm also having this problem even after re-linking. Also how can a warning "Warning: Unexpected pop" with no information as to what needs to be done or where the error is be a "solved issue". Shouldn't at least the warning be fixed to provide more info?

**Comment by radex** [comment]
@laurent22 because it's a React warning, not a warning from this library. If you figure out what causes this issue, let me know and maybe we can warn better users of this lib

**Comment by meghaptg** [comment]
Any update or progress on this? happening only for iOS, android works fine

**Comment by macavity23** [comment]
I got this error when I passed an `Animated.Value` in a style to a plain `View` instead of using `Animated.View`. HTH!
