### ISSUE TITLE
 Android Error : Native component for "BVLinearGradient" does not exist

### ISSUE THREAD

**Issue by BINAIMENG** [react-native-community/react-native-linear-gradient#329]
react-native : 0.55.4
react-native-linear-gradient : 2.4.0
![screenshot_2018-07-27-16-05-47-282_com gaozhimage](https://user-images.githubusercontent.com/19889708/43309297-ff47e082-91b6-11e8-9e9e-1d04c8a69651.png)
**I've already set up with Readme**
**How should I fix it**

**Comment by rdurel423** [comment]
I'm also getting this issue, on both platforms. I liked the library using `react-native link` and confirmed that it sets things up the way the document explains them to be.

**Comment by Volekss** [comment]
@BINAIMENG make sure not only to add this line
    `new LinearGradientPackage() // <---- and This!`
but don't also forget about an import
`import com.BV.LinearGradient.LinearGradientPackage; // <--- This!`

**Comment by rizwanatta** [comment]
@Volekss where to add these lines?

**Comment by Volekss** [comment]
@rizwanatta add the import line on the top of the file

**Comment by logicallyDimp** [comment]
for unexperienced developers like me... do pod install and rebuild app then happy hacking
