### ISSUE TITLE
Turn the gradient

### ISSUE THREAD

**Issue by Volekss** [react-native-community/react-native-linear-gradient#331]
Can I turn this gradient for example to -90deg?

**Comment by pedrojor2** [comment]
Have you tried setting the start and end props to relevant coordinate props?

E.g
```
    <LinearGradient
    start={{ x: 1, y: 0 }}
    end={{ x: 0, y: 0 }}
   >
   ...
   <LinearGradient />
```

On my end that flips what is a top to bottom gradient to a right to left one.

**Comment by Volekss** [comment]
> Have you tried setting the start and end props to relevant coordinate props?
> 
> E.g
> 
> ```
>     <LinearGradient
>     start={{ x: 1, y: 0 }}
>     end={{ x: 0, y: 0 }}
>    >
>    ...
>    <LinearGradient />
> ```
> On my end that flips what is a top to bottom gradient to a right to left one.

Thank you!
