### ISSUE TITLE
Opacity Gradient is White to Color Instead

### ISSUE THREAD

**Issue by jameshwangsmarkets** [react-native-community/react-native-linear-gradient#332]
I'm testing on Android right now and have 
`<LinearGradient colors={["transparent", "rgba(0, 0, 0, 1)"}></LinearGradient>`
But the the gradient goes from white to black instead of transparent to black. I've tested it when overlaid with something else and confirmed it isn't transparent.

**Comment by gabrielmoncea** [comment]
@jameshwangsmarkets how did you solve this?

**Comment by kulyk** [comment]
Hi @gabrielmoncea 

It's a pretty common issue, I've just submitted a PR extending the README with a solution
Please take a look: #479

**Comment by kulyk** [comment]
Hi @gabrielmoncea 

It's a pretty common issue, I've just submitted a PR extending the README with an example
Please take a look:
