### ISSUE TITLE
2.4.1 build.gradle _reactNativeVersion Problem

### ISSUE THREAD

**Issue by Kausta** [react-native-community/react-native-linear-gradient#336]
In version 2.4.1, android build.gradle has _reactNativeVersion, however it lacks 

     def _reactNativeVersion = _ext.has('reactNative') ? _ext.reactNative : '+';

and hence it gives an error, and one cannot build the project. Since package is automatically updated when version is set to ^2.4.0, this can become a problem to many.

**Comment by inanc-g** [comment]
Just in case someone needs a quick fix: you can change `^2.4.0` in your `package.json` to `2.4.0` (omit the caret) to fix this until #335 is merged and lands with the next patch.

**Comment by Lizhooh** [comment]
+1

**Comment by AnandKumar1100** [comment]
Not working for me also.
I remove ^ from 2.4.0 but still i m getting this error
My react native version is 0.55.4

**Comment by hesgroup** [comment]
@AnandKumar1100 @Lizhooh 
in 
`node_modules/react-native-linear-gradient/android/build.gradle`
Change 
`compileOnly "com.facebook.react:react-native:${_reactNativeVersion}" `
To
`compileOnly "com.facebook.react:react-native:0.55.4"  `
Fixed my problem.

**Comment by AnandKumar1100** [comment]
Thanks for the reply
I also change "compileOnly" to "compile". This worked for me
But we need some permanent solution as if we delete our node modules and reinstall them, then these changes will lost

**Comment by josetiagobispo** [comment]
in node_modules\react-native-linear-gradient\android\build.gradle
change  compileOnly "com.facebook.react:react-native:${_reactNativeVersion}"
to compile "com.facebook.react:react-native:0.55.4" or to compile "com.facebook.react:react-native:0.56"

**Comment by Kausta** [comment]
@AnandKumar1100 you need to do `npm install` or `yarn install` after you change the version to 2.4.0 without ^.

**Comment by Kausta** [comment]
5b4a5fb5bacbff85d293dbaf30b634f99d83b215 solves the issue.
