### ISSUE TITLE
Where is the 2.4.2 release?

### ISSUE THREAD

**Issue by mnapoli** [react-native-community/react-native-linear-gradient#338]
When installing this package using yarn the v2.4.2 is installed. However that version (and 2.4.1) does not exist in this repository (and additionally it has a bug, see: #336, but I guess that's not directly related).

Where are those 2 missing tags/releases?

**Comment by Kausta** [comment]
Current master is at 2.4.2, and #336 is solved in 2.4.2.

**Comment by mnapoli** [comment]
Thanks. But master is a branch, there is no 2.4.2 tag. Does that mean that 2.4.2 doesn't point to a specific commit? That could be a source of problems as that means that that version is not the same for everybody (or across time).

**Comment by didjo972** [comment]
I had the same issue but today, the current tag on npmjs is up to date. Try it on your project.

**Comment by mnapoli** [comment]
@didjo972 what do you mean by "tag"? There is no `2.4.1` and `2.4.2` tags in the repository (https://github.com/react-native-community/react-native-linear-gradient/tags), I don't understand how they could exist in npmjs?

**Comment by Kausta** [comment]
Npmjs versions are separated from git tags, they are not related. One can publish a new version without tagging it in git, or vice versa; however it is nicer to have the tags and published versions coincide.

**Comment by didjo972** [comment]
I don't know neither how nor why but yesterday i couldn't update the lib in 2.4.2. But today, i looked on https://www.npmjs.com/package/react-native-linear-gradient --> Versions and I saw 2.4.2
I tried to update the lib and it worked.

**Comment by mnapoli** [comment]
> Npmjs versions are separated from git tags, they are not related. One can publish a new version without tagging it in git, or vice versa; however it is nicer to have the tags and published versions coincide.

Thanks @Kausta that's much clearer now.

That situation still doesn't sound great though ^^

**Comment by yurykorzun** [comment]
Can we add a 2.4.2 tag to the repo?

**Comment by radex** [comment]
@yurykorzun Fixed
