### ISSUE TITLE
Build failed when running react-native run-android

### ISSUE THREAD

**Issue by stacheski** [react-native-community/react-native-linear-gradient#339]
When i run react-native run-android i get this error:

> FAILURE: Build failed with an exception.
> * Where:
> Build file '/lc_app/node_modules/react-native-linear-gradient/android/build.gradle' line: 21

> * What went wrong:
> A problem occurred evaluating project ':react-native-linear-gradient'.
> Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler. <

What should i do??

I did the install and the link.

**Comment by hazeeb** [comment]
@stacheski I had same issue and solved issue by opening this project in Android studio and upgraded the gradle version.

> RN Version : 0.56.0
> react-native-linear-gradient version : 2.4.2

**Comment by fanlide** [comment]
I have the same problem.
```
react-native: 0.55.4
react-native-linear-gradient:2.4.2
```

**Comment by fanlide** [comment]
I modify the `node_modules/react-native-linear-gradient/android/build.gradle`,solved it.
```
dependencies {
    compileOnly "com.facebook.react:react-native:+"
}
```
replace
```
dependencies {
    provided "com.facebook.react:react-native:+"
}
```

**Comment by ryanhomer** [comment]
This commit changes over to the newer `compileOnly` which may break your build if your version of gradle is too old (pre 3.5 ??). If you are unable to upgrade your gradle version at this time, I think version 2.4.0 of react-native-linear-gradient is the highest you can go for now.

**Comment by KasperOlesenMagnetix** [comment]
Same issue for me:

React-native: "0.56"
react-native-liniear-gradient: "^2.4.0"

Fixed by changing version of react-native-liniear-gradient in packages.json to "2.4.0"

**Comment by stacheski** [comment]
Using the 2.4.0 version worked.

Thank you guys!

**Comment by SwitchDestiny** [comment]
React-native: "0.55.4"
react-native-liniear-gradient: "^2.4.0"
That’s ♂Good！！

**Comment by r01010010** [comment]
@ryanhomer thanks for the explanation

**Comment by leticiamrosa** [comment]
It`s work for me too
    "react-native": "0.55.4",
    "react-native-linear-gradient": "^2.4.0",

try to : 
`npm install react-native-linear-gradient@2.4.0 --save`

**Comment by Y-JH** [comment]
i have solved this problem with updating gradle at version 3.0.1
