### ISSUE TITLE
Support for windows 10 uwp, currently support is only for wpf!!

### ISSUE THREAD

**Issue by vikramkalta** [react-native-community/react-native-linear-gradient#340]

**Comment by radex** [comment]
I'm closing this. UWP support would be great, but since this is a community-driven project, you have to volunteer an implementation in a pull request :)

**Comment by vikramkaltaIp** [comment]
@radex I had already created a native component for LinearGradient for uwp, ill see how i can bring that code here!! 
thanks for the reply!!

**Comment by radex** [comment]
@vikramkalta Awesome! Please share your code! I'll be happy to accept a PR

**Comment by vikramkaltaIp** [comment]
@radex sure, let me go through the library code and see how I can implement my component in same manner!

**Comment by nlabofa** [comment]
Any update on this @radex @vikramkalta

**Comment by vikramkalta** [comment]
@nlabofa really busy these days. If i get time, will surely complete this, but as of now no update from my side.
