### ISSUE TITLE
Encountered a problem： compileOnly()

### ISSUE THREAD

**Issue by fjsun123** [react-native-community/react-native-linear-gradient#346]
Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by sibelius** [comment]
Upgrade to gradle 3

**Comment by fjsun123** [comment]
How to upgrade to gradle 3

**Comment by sibelius** [comment]
check this https://github.com/react-native-community/react-native-camera/blob/master/docs/GradleUpgradeGuide.md

**Comment by fjsun123** [comment]
12/5000
Zěnme shēngjí hòu huì bù huì shénme wèntí
How will it be solved after upgrading?

**Comment by fjsun123** [comment]
Error after installing gradle 3

* What went wrong:
A problem occurred configuring root project 'BDX'.
> Could not resolve all files for configuration ':classpath'.
   > Could not download builder.jar (com.android.tools.build:builder:3.1.0)
      > Could not get resource 'https://maven.google.com/com/android/tools/build/builder/3.1.0/builder-3.1.0.jar'.
         > Read timed out

**Comment by fjsun123** [comment]
> Task :app:compileDebugJavaWithJavac FAILED
C:\Users\Administrator\Desktop\react native 8.1\git_BDX\BDX\android\app\src\main\java\com\bdx\MainApplication.java:6: 错误: 程序包com.BV.LinearGradient不存在
import com.BV.LinearGradient.LinearGradientPackage;
                            ^
C:\Users\Administrator\Desktop\react native 8.1\git_BDX\BDX\android\app\src\main\java\com\bdx\MainApplication.java:28: 错误: 找不到符号
            new LinearGradientPackage(),
                ^
  符号: 类 LinearGradientPackage
2 个错误

**Comment by fjsun123** [comment]
:app:compileDebugJavaWithJavac                 
C:\Users\Administrator\Desktop\react native 8.1\git_BDX\BDX\android\app\src\main\java\com\bdx\MainApplication.java:6: 错误: 程序包com.horcrux.svg不存在
import com.horcrux.svg.SvgPackage;             
                      ^
C:\Users\Administrator\Desktop\react native 8.1\git_BDX\BDX\android\app\src\main\java\com\bdx\MainApplication.java:28: 错误: 找不到符号
            new SvgPackage(),
                ^
  符号: 类 SvgPackage
2 个错误
Incremental compilation of 1 classes completed in 0.521 secs.
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by rahulbhankar786** [comment]
#339 please see this
