### ISSUE TITLE
import com.BV.LinearGradient.LinearGradientPackage;

### ISSUE THREAD

**Issue by fjsun123** [react-native-community/react-native-linear-gradient#347]
> Task :app:compileDebugJavaWithJavac FAILED
C:\Users\Administrator\Desktop\react native 8.1\git_BDX\BDX\android\app\src\main\java\com\bdx\MainApplication.java:6: 错误: 程序包com.BV.LinearGradient不存在
import com.BV.LinearGradient.LinearGradientPackage;
                            ^
C:\Users\Administrator\Desktop\react native 8.1\git_BDX\BDX\android\app\src\main\java\com\bdx\MainApplication.java:28: 错误: 找不到符号
            new LinearGradientPackage(),
                ^
  符号: 类 LinearGradientPackage
2 个错误

**Comment by radex** [comment]
I'm closing this because there's not enough information to help you. Send a new issue with more info if you believe this is a real issue.
