### ISSUE TITLE
Execution failed for task ':app:compileDebugJavaWithJavac'.  来帮忙看看

### ISSUE THREAD

**Issue by fjsun123** [react-native-community/react-native-linear-gradient#348]
:app:compileDebugJavaWithJavac                 
C:\Users\Administrator\Desktop\react native 8.1\git_BDX\BDX\android\app\src\main\java\com\bdx\MainApplication.java:6: 错误: 程序包com.horcrux.svg不存在
import com.horcrux.svg.SvgPackage;             
                      ^
C:\Users\Administrator\Desktop\react native 8.1\git_BDX\BDX\android\app\src\main\java\com\bdx\MainApplication.java:28: 错误: 找不到符号
            new SvgPackage(),
                ^
  符号: 类 SvgPackage
2 个错误
Incremental compilation of 1 classes completed in 0.521 secs.
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by radex** [comment]
I'm closing this since this is outside the scope of the library, and a simple workaround exists.
