### ISSUE TITLE
Border gradient with radius and transparent background ?

### ISSUE THREAD

**Issue by skbhardwaj** [react-native-community/react-native-linear-gradient#350]
Hello guys, 

I've been trying to add transparent background with a gradient border with radius, any idea?
Please refer to the screenshot of desired view:

<img width="259" alt="screen shot 2018-09-16 at 10 31 42 pm" src="https://user-images.githubusercontent.com/6456667/45600643-5eea9b80-ba00-11e8-9a1c-fa7b077d90be.png">

Thanks,
Shri.

**Comment by skbhardwaj** [comment]
Achieved the desired view with couple of other elements. Closing the issue. Thanks.

**Comment by asgvard** [comment]
@skbhardwaj Hi, could you provide an example of how did you manage to achieve this? Trying to do exactly the same, button with transparent background and gradient border with radius. Thanks!

**Comment by skbhardwaj** [comment]
Hello @asgvard - could you please refer https://snack.expo.io/@skbhardwaj/gradient-bordered-button. 

As of now this not working on expo .. because of invariant violation error, but you could try the code on your local.
Hopefully this should help.

Thanks,

**Comment by JustineOwl** [comment]
Hello @skbhardwaj. Does this solution work on ios devices? Because I can't achieve border radius effect with LinearGradient without using 'overflow: hidden' which I can't use. It works only on android

**Comment by NerdFaisal404** [comment]
please check this out
https://stackoverflow.com/questions/42734972/react-native-linear-gradient-only-red-border-is-visible-on-ios/57782586#57782586

**Comment by chenop** [comment]
@NerdFaisal404 your link is a good example but the inner background is white (not transparent).
would be happy to see an example as well.
