### ISSUE TITLE
How to specifically add gradient just for the text and icons color?

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [react-native-community/react-native-linear-gradient#354]
How to specifically add gradient just for the text and icons color?

**Comment by radex** [comment]
you could try to do this by masking (e.g. https://facebook.github.io/react-native/docs/maskedviewios), but it's kind of outside the scope of this library. Let me know if you get this to work

**Comment by SPCXC** [comment]
> How to specifically add gradient just for the text and icons color?

do you let it work just for text,or do you have any workaround?

**Comment by ManigandanRaamanathan** [comment]
Found that there is a specific library available for that specifically

**Comment by radex** [comment]
@ManigandanRaamanathan would you mind sending a quick PR adding this in FAQ/troubleshooting/protips to the README? A lot of people are asking about this

**Comment by radex** [comment]
@ManigandanRaamanathan thanks for the link — could you please send a very quick PR? You can edit the Readme from the browser. It will help a lot of people :)

**Comment by ManigandanRaamanathan** [comment]
Sure

**Comment by SPCXC** [comment]
> > @ManigandanRaamanathan would you mind sending a quick PR adding this in FAQ/troubleshooting/protips to the README? A lot of people are asking about this
> 
> @radex
> Using this:
> https://github.com/iyegoroff/react-native-text-gradient
> 
> slightly buggy, but it works

Not work during release build
