### ISSUE TITLE
Transparent gradient.

### ISSUE THREAD

**Issue by tskorupka** [react-native-community/react-native-linear-gradient#358]
Hi,

I've tried to make white-to-transparent gradient for end of my view.

```
<LinearGradient style={style.bottomGradient} colors={['transparent', '#FFF']}/>
```

Currently on Android it is working, but on iOS there is some shadow that is black.

Also I could not attach screenshoots of my app, maybe I would add them soon, if I'd manage to make example.

**Comment by alburdette619** [comment]
@tskorupka is it like this?  This is what I'm seeing trying to apply a multi opacity gradient to transparent.

<img width="108" alt="screen shot 2018-10-22 at 5 06 55 pm" src="https://user-images.githubusercontent.com/22638838/47319532-ebe6cd00-d61c-11e8-8feb-1fc09fdb1f2f.png">

**Comment by tskorupka** [comment]
![gradient_1](https://user-images.githubusercontent.com/7491616/47355715-5d2c8b80-d6c2-11e8-827e-8fd7aab52766.png)

This is result working on Android.

![gradient_2](https://user-images.githubusercontent.com/7491616/47355793-982ebf00-d6c2-11e8-8cac-880ad8dd6ebb.jpeg)

This is result working on iOS.

So LinearGradient is inside Animated.ScrollView and for iOS it is showing some black shadow instead of being transparent.

**Comment by tskorupka** [comment]
Below is Android example.

![gradient_1](https://user-images.githubusercontent.com/7491616/47355860-ce6c3e80-d6c2-11e8-93d4-a153e8331768.png)

Below is iOS example.

![gradient_2](https://user-images.githubusercontent.com/7491616/47355866-d5934c80-d6c2-11e8-8e4f-2622b2a16852.jpeg)

LinearGradient is placed in Animated.ScrollView.

Colors are `#FFF` and `transparent` values.

For Android it is working without any doubt, but for iOS it is showing black shadow or something.

**Comment by radex** [comment]
`transparent` is the same as **black** with zero opacity, so a white→transparent gradient will necessarily go from invisible black, through half-visible gray, to fully visible white.

Correct me if I'm wrong, but I believe this is the way it works in a lot of places, and isn't actually specific to this library. We could note this in the readme documentation as a common pitfall

**Comment by tskorupka** [comment]
@radex so if it is expecteda action we can close this.

**Comment by radex** [comment]
@Sangrene would you mind contributing to the README file with this pro tip? A lot of people don't understand this about `transparent`

**Comment by Sangrene** [comment]
Sure, will send a PR for this asap !

**Comment by naazim-db** [comment]
Make sure that the parent container of `LinearGradient` has a background color set to white. This fixed the weird grey issue for me!

**Comment by naazim** [comment]
Make sure that the parent container of LinearGradient has a background color set to white. This fixed the weird grey issue for me!

**Comment by Dror-Bar** [comment]
In my case I needed to use 3 parameters inside the array.
I wanted to achieve black at bottom gradient upwards with 0.2 opacity. For me it looked like this:
`colors={["black", "#00000033", 'ffffff00']}`

**Comment by obiwankenoobi** [comment]
@Sangrene works like a charm!! Thank you

**Comment by alfonsodev** [comment]
non of the solutions seem to work with version `2.5.4`,
also REAME doesn't explain how to it, any ideas ?

**Comment by florinlazau** [comment]
@tskorupka, can you please share your code. I'm trying to add a gradient at a bottom of a flat list bit without luck. 

Thanks

**Comment by enaluz** [comment]
This worked perfectly for me.

`
<LinearGradient
  colors={["rgba(0,0,0,0.7)", "rgba(0,0,0,0.4)", "rgba(0,0,0,0)"]}
  start={{ x: 0, y: 1 }}
  end={{ x: 0, y: 0 }}>
`

**Comment by erikfenriz** [comment]
For some reason, it doesn't work for me. 
I am trying to attach a white to transparent gradient at the bottom with keyboard avoiding view RN component. Instead, I get a solid gray container.

Before activating keyboard:
![Simulator Screen Shot - iPhone 11 Pro - 2020-06-08 at 12 14 09](https://user-images.githubusercontent.com/25347909/84016937-abb99700-a986-11ea-814a-9c8ad8b994b2.png)

After activating keyboard:
![Simulator Screen Shot - iPhone 11 Pro - 2020-06-08 at 12 16 51](https://user-images.githubusercontent.com/25347909/84016988-c12ec100-a986-11ea-8487-43a1e454eee1.png)

code:
`        <>
        <SafeAreaView style={styles.container}>
                <ScrollView>
                    <View style={styles.headingContainer}>
                        <Text style={styles.heading}}</Text>
                        <View style={[styles.headingHighlight, term ? styles.headingHighlightResults : styles.headingHighlightSearching]}/>
                    </View>
                    <SearchBar term={term} onTermChange={setTerm}/>
                    {term ? <SearchResults/> : <Categories/>}
                </ScrollView>

        </SafeAreaView>
            <KeyboardAvoidingView keyboardVerticalOffset={82} behavior='position'>
                <LinearGradient colors={['#FFFFFF00', '#FFFFFF']}
                    style={{height: 53}}
                />
            </KeyboardAvoidingView>


    </>`

I tried putting it inside SafeAreaView and tweaked styles - no effect.

**Comment by sankaSanjeeva** [comment]
This is work for android
```
<ScrollView fadingEdgeLength={100}>
  ... scroll view content ...
</ScrollView>
```

**Comment by lbrun25** [comment]
> Make sure that the parent container of LinearGradient has a background color set to white. This fixed the weird grey issue for me!

I set the background of the parent as transparent and it works:
```typescript
<View style={{
  height: height,
  position: 'absolute',
  bottom: 0,
  left: 0,
  right: 0,
  backgroundColor: "transparent"
}}>
  <LinearGradient
    style={{
      height: height
  }}
    colors={[Colors.rgba(theme.colors.background, 0.1), Colors.rgba(theme.colors.background, 0.7)]}
  />
</View>
```
