### ISSUE TITLE
Remove PropTypes?

### ISSUE THREAD

**Issue by radex** [react-native-community/react-native-linear-gradient#359]
Looks like React Native is moving away from using PropTypes in favor of relying on Flow & TypeScript.

Do you think it's appropriate to move in the same direction in libraries like `react-native-linear-gradient`? Asking for feedback from previous maintainers: @GantMan @sibelius @dgladkov and anyone interested.

If I get a "go", I'll be happy to contribute cleanup of PropTypes

**Comment by GantMan** [comment]
personally, I feel proptypes are a decent runtime check if you don't have TypeScript or Flow in place.

Are you suggesting removing PropTypes and that's it?  Or are you suggesting adding Flow or TypeScript and then removing PropTypes?

**Comment by pontusab** [comment]
Also in React-native `0.58.0-rc.0` `ColorPropType.js` has been moved to `DeprecatedColorPropType.js` so `react-native-linear-gradient` breaks with latest versions. @radex have you started or do you need help?

**Comment by radex** [comment]
@pontusab done. lmk if it works correctly
