### ISSUE TITLE
Failed to capture snapshot of input files for task ':app:bundleReleaseJsAndAssets' property '$1' during up-to-date check.

### ISSUE THREAD

**Issue by agoiabel** [react-native-community/react-native-linear-gradient#361]
After doing npm install react-native-linear-gradient --save, if i link automatically using (react-native link react-native-linear-gradient) or manually.

I won't be able to build again with error message:

```
* What went wrong:
Failed to capture snapshot of input files for task ':app:bundleReleaseJsAndAssets' property '$1' during up-to-date check.
> Could not list contents of '/Users/admin/code/DSTestClient/node_modules/fsevents/node_modules/.bin/node-pre-gyp'. Couldn't follow symbolic link.
```

**Comment by agoiabel** [comment]
I use react-native v0.57.3

**Comment by holoc285** [comment]
Many thanks bro.

**Comment by Samiksha19** [comment]
@agoiabel saved my day..thanks

**Comment by wangchao1002** [comment]
Thanks 😊

**Comment by ytt123** [comment]
my rn version is 0.57.8 .i can run but can not package

**Comment by mmustafaozdemir** [comment]
> my rn version is 0.57.8 .i can run but can not package

I have the same problem. Did you find a solution?
