### ISSUE TITLE
Pick the color based point coordinates [Feature question]

### ISSUE THREAD

**Issue by alexsmartens** [react-native-community/react-native-linear-gradient#367]
I am looking to create a gradient scale for a dashboard. Is it possible to create a gradient with some values say from 0% to 100% and pick the color from this scale based on the current sensor value, something like this:

![image](https://user-images.githubusercontent.com/26261714/48104307-ed112000-e200-11e8-9aff-6aa5fbcf3b40.png)

I started implementing this idea with react-native-svg, but I don't think this is possible with the svg library alone ([my svg issue](https://github.com/react-native-community/react-native-svg/issues/838))

**Comment by radex** [comment]
sorry, this is outside the scope of this library. You can calculate color based on gradients using some basic color math - check out `tinycolor2` — it's possible this can help you
