### ISSUE TITLE
There is a problem with the BLVLinearGradient.xcodeproj

### ISSUE THREAD

**Issue by smooJitter** [react-native-community/react-native-linear-gradient#368]
It appears BLVLinearGradient.xcodeproj file is inoperable.  I received an xcode area citing unable to open the file.  I copied over a version of the file from a previously working version of my project.  This fixed the problem

**Comment by radex** [comment]
what version of Xcode are you running? @smooJitter ?

**Comment by duongthienlee** [comment]
I'm also facing the same problem, I'm using Xcode version 10
The error show: requireNativeComponent: "BLVLinearGradient" was not found in the UIManager

**Comment by radex** [comment]
@duongthienlee that's not the same problem — looks like you didn't link the native module properly

**Comment by duongthienlee** [comment]
Oh my bad, however, I tried to run react-native link, but it still doesn't work. I will try to add it manually on Xcode then. Hope it's gonna work.

> @duongthienlee that's not the same problem — looks like you didn't link the native module properly

**Comment by smooJitter** [comment]
@radex I was using xcode 9.2.  Sorry, I could have been a bit more distributive about my setup.

RN: 0.56.0
R: 16.4.1

I tried linking via react-native link and also manually.  In both cases merely selecting BLVLinearGradient.xcodeproj would result in an xcode popup error indicating the file could not be opened.  Clearly, the file is present (verified through manual linking).   I even tried to install an early version of the plugin but to no avail.  

To fix the problem, I copied the BLVLinearGradient.xcodeproj from an early version of my project.  I expect to run into problems if I need to add another package (I think yarn does some sort of integrity check).   In fact, the xcode error mentioned BLVLinearGradient had some sort of project integrity issue.

**Comment by radex** [comment]
@smooJitter Is there anything stopping you from upgrading to _at least_ Xcode 9.4?

**Comment by smooJitter** [comment]
I can do that.

**Comment by radex** [comment]
closing issue - reopen if issue persists on Xcode 9.4

**Comment by elmarti** [comment]
Or, if you're a React Native n00b (like me), actually run the XCode build after linking
