### ISSUE TITLE
Angel doesn't work on IOS

### ISSUE THREAD

**Issue by ErrorPro** [react-native-community/react-native-linear-gradient#379]
According to the docs you can pass three additional props: useAngle, angle, angleCenter. Has anyone got it working? It doesn't work on `"react-native": "0.57.1"`, passing this props doesn't give you any result like at all. Any help would be appreciated.

**Comment by jasongaare** [comment]
I'd check to make sure you are on the latest version -- ran into a similar issue but once I upgraded all worked as expected.

**Comment by evert-smit** [comment]
@ErrorPro can you provide a code sample?

@jasongaare What version of react-native are you on? I'm on 0.57.8 now with react-native-linear-gradient at 2.5.3 and so far, providing an angle is not working for me yet (iOS).

**Comment by ErrorPro** [comment]
Thanks guys, upgrading solved the issue!
