### ISSUE TITLE
Do this library support an equivalent of CSS repeating-linear-gradient?

### ISSUE THREAD

**Issue by jpamarohorta** [react-native-community/react-native-linear-gradient#380]
Hello, I looked all over the docs and opened/closed issues for a reference to repeating gradients like CSS **repeating-linear-gradient** (https://developer.mozilla.org/en-US/docs/Web/CSS/repeating-linear-gradient) but couldn't find anything.

Are these types of gradients not supported or am I completely missing something?

Thanks!

**Comment by radex** [comment]
Sadly not! But contributions are welcome
