### ISSUE TITLE
Could not find method compileOnly() for arguments [com.facebook.react:react-native:

### ISSUE THREAD

**Issue by JosephMulder** [react-native-community/react-native-linear-gradient#381]
Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Using React-native 0.51.0 and i'm getting this error, I tried changing compileOnly to implementation and compile but that didn't change anything and I couldn't find a version of react-native-linear-gradient that worked. Does anyone a version that would work with 51.0?

**Comment by sibelius** [comment]
Use latest version of react native, and update your grades version

**Comment by JosephMulder** [comment]
> Use latest version of react native, and update your grades version

That isn't really an option for me at the time, any other approach you can think of?

**Comment by sibelius** [comment]
only update gradle
