### ISSUE TITLE
[Doc] Can not access screenshots for ios manual link

### ISSUE THREAD

**Issue by PierreCapo** [react-native-community/react-native-linear-gradient#382]
In https://github.com/react-native-community/react-native-linear-gradient#manually the screenshot links are not working and I got a "Forbidden access" messages. Would it be possible to fix it please ? :)

**Comment by arnoldc** [comment]
i can experience it too
mine says
"This site can’t be reached url.brentvatne.ca’s server IP address could not be found"

**Comment by radex** [comment]
fixed
