### ISSUE TITLE
BVLineargradient was not found in the UIManager

### ISSUE THREAD

**Issue by akhilsanker** [react-native-community/react-native-linear-gradient#395]
Hi,
Iam using "react-native-linear-gradient": "^2.4.0". In iOS its working perfectly. But in android I am getting an error like:
 "BVLineargradient was not found in the UIManager".

Does anyone know any workaround?
Any solution is appreciable.
 Thanks

**Comment by pramodkumar005** [comment]
-- Step 1 
execute this command
"react-native upgrade"
-- Step 2 
After this manually link react-native-linear-gradient
-- Step 3
Build the app
React-native run-android

**Comment by Agungkes** [comment]
I just have need to execute this command after installing _react-native-linear-gradient_ and everything working as expected.
`react-native run-android `

**Comment by akhilsanker** [comment]
Solved by adding 'new LinearGradientPackage()'  in 'getPackages()' in MainApplication.java.

Thanks

**Comment by michaelAdewunmi** [comment]
I am presently having this same problem but in my case, I am using Expo? Please anyone with a workaround on how I solve this problem.

Since i'm using expo, I do not have access to MainApplication.java file in the android folder. 

Also, Running react-native upgrade isn't working for me.

Is there any workaround to this please. Thanks!?

**Comment by cmcaboy** [comment]
@michaelAdewunmi I don't believe this library supports expo since native modules are required.

**Comment by rosnaib11** [comment]
I had same issue with expo

**Comment by findli** [comment]
why it's closed?

**Comment by schumannd** [comment]
Yes, still randomly happens to my build as well, even though everything used to work. Pretty random, should be reopened

**Comment by rosnaib11** [comment]
Use `expo install expo-linear-gradient` instead it works forme

**Comment by victorbruce** [comment]
@rosnaib11 solution worked for me!
Import it by adding the code: `import {LinearGradient} from 'expo-linear-gradient`

**Comment by Monstercat666** [comment]
> @rosnaib11 solution worked for me!
> Import it by adding the code: `import {LinearGradient} from 'expo-linear-gradient`
Thank you so much

**Comment by mesutche** [comment]
Check your package.json file if react-native-linear-gradient was exist or not. Then rebuild the app . Mostly error will gone after build process .

**Comment by theshook** [comment]
> 
> 
> @rosnaib11 solution worked for me!
> Import it by adding the code: `import {LinearGradient} from 'expo-linear-gradient`

Thank you so much!

**Comment by andreydos** [comment]
I do not want to use Expo in my project but I still get error "Invariant Violation: requireNativeComponent: "BVLinearGradient" was not found in the UIManager." But on ANDROID, not iOS. iOS works fine. 
"react-native": "^0.62.0"
"react-native-linear-gradient": "^2.5.6"

I try to use all things like:
rm -rf node_modules 
adding 'new LinearGradientPackage()' in 'getPackages()' in MainApplication.java.
cd android && ./gradlew cleanBuildCache
and a lot of others but witout any succes in Android

**Comment by jeafgilbert** [comment]
@andreydos I just fixed this issue by rolling back to working state and do these steps:
1) Stop Metro
1) Run `npm install react-native-linear-gradient --save`
2) Run `npx pod-install ios` (for iOS)
3) Add `import LinearGradient from 'react-native-linear-gradient;` in my page file
4) Test with:
`<LinearGradient colors={['#4c669f', '#3b5998', '#192f6a']} style={styles.linearGradient}>
						<Text style={styles.buttonText}>Sign in with Facebook</Text>
					</LinearGradient>`
5) Add styles:
`linearGradient: {
		paddingLeft: 15,
		paddingRight: 15,
		borderRadius: 5
	},
	buttonText: {
		fontSize: 18,
		fontFamily: 'Gill Sans',
		textAlign: 'center',
		margin: 10,
		color: '#ffffff',
		backgroundColor: 'transparent',
	}`
5) Run `react-native run-android`

(React Native 0.62.2)

It's working now.

**Comment by KalidassM01** [comment]
> @andreydos I just fixed this issue by rolling back to working state and do these steps:
> 
> 1. Stop Metro
> 2. Run `npm install react-native-linear-gradient --save`
> 3. Run `npx pod-install ios` (for iOS)
> 4. Add `import LinearGradient from 'react-native-linear-gradient;` in my page file
> 5. Test with:
>    `<LinearGradient colors={['#4c669f', '#3b5998', '#192f6a']} style={styles.linearGradient}> <Text style={styles.buttonText}>Sign in with Facebook</Text> </LinearGradient>`
> 6. Add styles:
>    `linearGradient: { paddingLeft: 15, paddingRight: 15, borderRadius: 5 }, buttonText: { fontSize: 18, fontFamily: 'Gill Sans', textAlign: 'center', margin: 10, color: '#ffffff', backgroundColor: 'transparent', }`
> 7. Run `react-native run-android`
> 
> (React Native 0.62.2)
> 
> It's working now.

Its working for iOS also. Very helpful. Thanks alot.

**Comment by KalidassM01** [comment]
@jeafgilbert  Its working for iOS also. Very helpful. Thanks alot man.

**Comment by imvarnit1996** [comment]
> Use `expo install expo-linear-gradient` instead it works for me

worked.

**Comment by zabojad** [comment]
I'm having this issue on Android and RN 0.61.5 and can't get rid of it even after removing node_modules and re-installing... Anyone else in that case?

**Comment by imvarnit1996** [comment]
> I'm having this issue on Android and RN 0.61.5 and can't get rid of it even after removing node_modules and re-installing... Anyone else in that case?

install expo-linear-gradient from expo.

**Comment by snh3003** [comment]
> @rosnaib11 solution worked for me!
> Import it by adding the code: `import {LinearGradient} from 'expo-linear-gradient`

This thing worked for me!!!!!

**Comment by zabojad** [comment]
> > I'm having this issue on Android and RN 0.61.5 and can't get rid of it even after removing node_modules and re-installing... Anyone else in that case?
> 
> install expo-linear-gradient from expo.

I'm not using expo, so how would that package work for me?

**Comment by xesk84** [comment]
Not working on Android. RN:0.63.2 WITHOUT expo.

**Comment by appfr3d** [comment]
A bit late, but maybe someone still encounters this error.
I fixed this by adding this line to my Podfile:
`pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'`
and doing a pod install inside the ios folder in my terminal.

**Comment by satbirkira** [comment]
Re-doing a build from xcode worked for me.

**Comment by aanbari1337** [comment]
> @rosnaib11 solution worked for me!
> Import it by adding the code: `import {LinearGradient} from 'expo-linear-gradient`

where i have to import it

**Comment by KthProg** [comment]
None of these solutions work for me RN 0.65, it's just broken for Android.

**Comment by kyzsu** [comment]
I have tried all the possible answers given above but did not seem to work.  RN 0.64.2

**Comment by aliwaqar981** [comment]
still getting this error on RN 0.67.2. Android is broken. I'm not using expo. Any solution?

**Comment by starprince7** [comment]
Me too also tried every possible soultion above in my expo project. But it still dosent work.

**Comment by josanjohnata** [comment]
This step by step worked for me. [react-native-linear-gradient](https://github.com/react-native-linear-gradient/react-native-linear-gradient) 🚀

**Comment by IgorMing** [comment]
The doc isn't updated properly. For me, it was fixed by basically running `pnpx pod-install` (or, of course, `npx pod-install`)

**Comment by DininduChamikara** [comment]
> Use `expo install expo-linear-gradient` instead it works for me

Thank you so much!

**Comment by sohaibzahid197** [comment]
I am Working React Native Cli

I install "npm install react-native-linear-gradient"

And Linear Gradient not Working. 


Error:

 BVLinearGradient was not found in the UIManager
