### ISSUE TITLE
BVLinearGardient was not found in the UIManager IOS

### ISSUE THREAD

**Issue by AilsonFreire** [react-native-community/react-native-linear-gradient#404]
![Simulator Screen Shot - iPhone 5s - 2019-03-21 at 16 14 03](https://user-images.githubusercontent.com/9551815/54778781-5a43b180-4bf4-11e9-81f8-966d87e0d53a.png)

**Comment by AilsonFreire** [comment]
I just forget to use pode install

**Comment by vongohren** [comment]
@AilsonFreire how are you installing it? Cause when I use pod install I get errors consering react and stuff

**Comment by AilsonFreire** [comment]
I just follow the instructions to install and in IOS folder I used pod install

**Comment by vongohren** [comment]
@AilsonFreire But do you have something like this code in your podfile:

```
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'jschelpers',
    'cxxreact',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTWebSocket',
  ]
```

Because when I just follow the instructions I get a react version 0.11 installed, and that makes things crash further down the line when trying to compile?
