### ISSUE TITLE
BVLinearGradient.xcodeproj file couldn't be opened

### ISSUE THREAD

**Issue by stylianospanagakos** [react-native-community/react-native-linear-gradient#407]
I'm trying to manually install linear gradient to my XCode project following the instructions found [here](https://github.com/react-native-community/react-native-linear-gradient) but when I try to click `BVLinearGradient.xcodeproj` in order to go to the `Build Settings` I get an error saying **The file couldn't be opened** since it looks like `BVLinearGradient.xcodeproj` is an empty project. Anyone has any clue why this is happening?

I'm using `"react-native-linear-gradient": "^2.4.3"`, and `"react-native": "0.49.5"`.

**Comment by VitorBrangioni** [comment]
Same problem. Any solution?

**Comment by stylianospanagakos** [comment]
@VitorBrangioni, the solution to my problem was to upgrade my version of XCode from 9.2 to 10.2. As soon as I did it, `BVLinearGradient.xcodeproj` somehow pulled all the right header and implementation files and started working fine. Hopefully, your problem can be resolved the same way so I'm closing the ticket for now.
