### ISSUE TITLE
[Request] Support dithering via CGGradient

### ISSUE THREAD

**Issue by asamiller** [react-native-community/react-native-linear-gradient#42]
I tried using this for large gradient backgrounds in my app, but after doing some research, it looks like CAGradientLayer isn't dithered, CGGradient however is. It would be awesome to have a dither option that would use CGGradient for higher quality gradients.

**Comment by brentvatne** [comment]
I don't have any plans to do this but I would accept a PR!

**Comment by sibelius** [comment]
fixed here https://github.com/react-native-community/react-native-linear-gradient/pull/296

try it out using master
