### ISSUE TITLE
requireNativeComponent: BVLinearGradient was not found in UIManager

### ISSUE THREAD

**Issue by NalinKamboj** [react-native-community/react-native-linear-gradient#422]
I am working with RN and RNLG on Android and I keep getting the following error 
> Invariant Violation: requireNativeComponent: "BVLinearGradient" was not found in the UIManager.

I have followed all steps listed online to link the dependencies properly. 

1. 

    include ':react-native-linear-gradient'
    project(':react-native-linear-gradient').projectDir = new File(rootProject.projectDir,'../node_modules/react-native-linear-gradient/android')
2)

    ...
    dependencies {
        implementation project(':react-native-linear-gradient')
        ...

3)

    import com.BV.LinearGradient.LinearGradientPackage;
    ....
    @Override
    protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                    new MainReactPackage(),
                    new LinearGradientPackage()

            );
    }

Android Studio project builds properly as well.
Also, I've linked RNLG using NPM with my RN project.
Here's a screenshot of the error - 

![Screenshot_20190621-171630](https://user-images.githubusercontent.com/20097276/59937263-e52d8580-9449-11e9-8280-935d1328c8c1.jpg)

Any help appreciated! 
Thanks!

**Comment by NalinKamboj** [comment]
I added 
  
    addPackage(new LinearGradientPackage())

inside the other activity which was running RN code. I initially added that line ONLY to MainApplication.java as shown on the main documentation page.

**Comment by Turgut-Kurt** [comment]
> I added
> 
> ```
> addPackage(new LinearGradientPackage())
> ```
> 
> inside the other activity which was running RN code. I initially added that line ONLY to MainApplication.java as shown on the main documentation page.
Thank you for your answer.But , didn't work on me

**Comment by shohailahm** [comment]
The issue is with linking [comment](https://github.com/react-native-community/react-native-linear-gradient/issues/434#issuecomment-523166497) helped

**Comment by spyshower** [comment]
Why isn't this fixed yet?

**Comment by abhi-laksh** [comment]
After linking the library, terminate the dev-server and run the following command:
> react-native run-android
Make sure your device/emulator is active. This worked for me.
