### ISSUE TITLE
Using LinearGradient in react-native 0.59.9 causes Invariant volation in android

### ISSUE THREAD

**Issue by PythxnBite** [react-native-community/react-native-linear-gradient#423]
# Bug
Using LinearGradient tag in react-native from one class to another seems to be sending an empty return value during export. i have tried all the legible ways to export and even tried in a new app.

Screenshots:
![Screenshot from 2019-06-22 22-09-14](https://user-images.githubusercontent.com/37470033/59966442-8136ba00-953a-11e9-832c-e912d3024569.png)

## Environment info

React native info output:

```bash
React Native Environment Info:
    System:
      OS: Linux 5.0 Pop!_OS 19.04
      CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
      Memory: 140.89 MB / 7.66 GB
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/bin/node
      Yarn: 1.16.0 - /usr/bin/yarn
      npm: 6.9.0 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Library version: 2.5.4

## Steps To Reproduce

1. Install  LinearGradient using yarn add react-native-linear-gradient

2. wrap Button from react-native-paper in a separate file and export the class to app.js

Describe what you expected to happen:

1. A gradient to be formed in the button or view

2. For the class to pass a compound value instead of null

## Reproducible sample code

App.js

```
import React, { Component } from 'react'
import { LG } from './LG'

export default class App extends Component {
	render() {
		return <LG />
	}
}
```

LG.js

```
import React, { Component } from 'react'
import { View, Text } from 'react-native'
import { LinearGradient } from 'react-native-linear-gradient'

class LG extends Component {
	render() {
		return (
			<LinearGradient colors={['#fcd62c', '#f6883d']}>
				<View>
					<Text>Hello Boris</Text>
				</View>
			</LinearGradient>
		)
	}
}

export default LG
```

**Comment by Mhmdabed11** [comment]
I am facing the same issue

**Comment by PythxnBite** [comment]
Yeah. I'm still unable to resolve this. Donno what to do.
Can you tell me more about your case? Maybe it can help us.

**Comment by PythxnBite** [comment]
> I am facing the same issue

Did you try using
 `react-native link react-native-linear-gradient`

it worked for me just now.
this is the code I tried

import React from 'react'
import { View, Text } from 'react-native'
import LinearGradient from 'react-native-linear-gradient'

```
class LGEX extends React.Component {
	render() {
		return (
			<LinearGradient colors={['black', 'white']} style={{ flex: 1 }}>
				<View
					style={{
						flex: 1,
						justifyContent: 'center',
						alignItems: 'center',
						backgroundColor: 'transparent'
					}}>
					<Text>Hello</Text>
				</View>
			</LinearGradient>
		)
	}
}

export default LGEX
```

and this is the App file

```
import React, { Component } from 'react'
import { Platform, StyleSheet, Text, View } from 'react-native'
import LGEX from './lgex'

export default class App extends Component {
	render() {
		return <LGEX />
	}
}
```

Hope this helps you :)

**Comment by Mhmdabed11** [comment]
My problem was that when i tried to inspect an `RTCView`, it gave me invariant violation error. Now I reinstalled the library again and  added `react-native link react-native-linear-gradient`  and it worked. Thank you !!

**Comment by PythxnBite** [comment]
I also found that the main problem for me was that I use 
`import { LinearGradient } from 'react-native-linear-gradient`
instead of 
`import LinearGradient from 'react-native-linear-gradient`

P.S : posting now as i came across this problem again

**Comment by shiroze** [comment]
meet this problem when using :
```
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-linear-gradient": "^2.5.6",
```
