### ISSUE TITLE
EISGIT: react-native-linear-gradient: Appears to be a git repo or submodule.

### ISSUE THREAD

**Issue by Jatin-007** [react-native-community/react-native-linear-gradient#430]
# npm error

Following the instructions to add this library to my project, i realized that this error started to throw whenever i performed an action to install any other library or even performed `npm install`. 

To overcome this error, tried-
1. removing and re-installing node modules, performing `npm i` again to verify if it still exists
2. removing only `react-native-linear-gradient` library and installing it again and performing `npm` to verify if the error still exists
3. tried installing another library. 

```
npm ERR! path /Users/xx/node_modules/react-native-linear-gradient
npm ERR! code EISGIT
npm ERR! git /Users/xx/node_modules/react-native-linear-gradient: Appears to be a git repo or submodule.
npm ERR! git     /Users/xx/node_modules/react-native-linear-gradient
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
```

Only happening with this library.

**Comment by IsmailAlam786** [comment]
bump

**Comment by muratonay1** [comment]
I get the same error

**Comment by Jatin-007** [comment]
@radex could you please provide the reason for closing this? or a solution to this?

**Comment by taixw2** [comment]
same

**Comment by Jujenji** [comment]
Get the same error. Could this be an issue with the update of the expo-cli ? It seems the upgrade on v. 3.X has already a few issues brought up. Maybe this is one of them ?

**Comment by mboettcher** [comment]
fixed it for me:

* manually change version to 2.5.6 in package.json
* remove all node modules (rm -rf node_modules)
* reinstall everything (npm install)
