### ISSUE TITLE
no such file or directory: Release-iphonesimulator/libBVLinearGradient.a

### ISSUE THREAD

**Issue by ahmadi-kemis** [react-native-community/react-native-linear-gradient#436]
Hi, Can You help me. I'm stuck thie error.

<img width="1015" alt="Screen Shot 2019-09-06 at 8 59 56 AM" src="https://user-images.githubusercontent.com/54032923/64395588-fd926100-d084-11e9-9178-2cb01c673307.png">

**Comment by ahmadi-kemis** [comment]
> Hi, Can You help me. I'm stuck thie error.
> 
> <img alt="Screen Shot 2019-09-06 at 8 59 56 AM" width="1015" src="https://user-images.githubusercontent.com/54032923/64395588-fd926100-d084-11e9-9178-2cb01c673307.png">

**Comment by alanjonesrios** [comment]
Same here

**Comment by tronglv92** [comment]
@alanjonesrios I don't know why errors but I fix issue by:
https://drive.google.com/file/d/12qT0Z7rfYrhnHYYECzVOAEMTjiPS2vJr/view
https://drive.google.com/file/d/1LZ2CrOHydBjy479r9aEyMkvqqSbIdDLm/view
It will run success
Sorry my bad english
