### ISSUE TITLE
‼️ Looking for a maintainer ‼️

### ISSUE THREAD

**Issue by radex** [react-native-community/react-native-linear-gradient#438]
As you might have noticed, pull requests in this repository sit unreviewed for a long time, and nobody replies to Issues.

The problem is that **nobody actively maintains this repository** — despite being very popular. I took over maintenance some time ago after a few previous maintainers, but after a while of cleaning up things I cared about personally for this library, I lost interest — I barely use this library anymore, and I have [two](https://github.com/Nozbe/watermelondb/) [other](https://github.com/nozbe/zacs) libraries to maintain.

### This is where _you_ come in

Clearly, a lot of people use this library, and there's interest in helping out (seeing PRs from @friederbluemle @dulmandakh and others). So, if you're interested in being a maintainer (there doesn't have to be just one maintainer, if more people want to help out - that's even better - as it means less maintenance work per person) — please comment here!

![](https://github.com/Nozbe/WatermelonDB/raw/master/assets/needyou.jpg)

**Comment by dulmandakh** [comment]
I'm in 👍

**Comment by friederbluemle** [comment]
Sounds good, count me in as well 👍 Thanks!

**Comment by radex** [comment]
@dulmandakh @friederbluemle You have write access to the repo now!
