### ISSUE TITLE
Library not found for -lBVLinearGradient with use_frameworks! in Podfile (RN61)

### ISSUE THREAD

**Issue by iRyusa** [react-native-community/react-native-linear-gradient#443]
# Bug

My project doesn't compile anymore when removing `use_frameworks!` (some other dependencies doesn't like this option now...)

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 85.66 MB / 16.00 GB
    Shell: 5.5.1 - /usr/local/bin/zsh
  Binaries:
    Node: 10.15.0 - /var/folders/3m/jky4sjj912103str4gpv8gk40000gn/T/yarn--1572456493742-0.9657050856585054/node
    Yarn: 1.15.2 - /var/folders/3m/jky4sjj912103str4gpv8gk40000gn/T/yarn--1572456493742-0.9657050856585054/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 24, 28, 29
      Build Tools: 28.0.3, 29.0.1
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: 0.61.3 => 0.61.3
✨  Done in 4.32s.
```

```
➜  ios git:(feat/add-paiment-card) ✗ pod --version
1.8.4
```

Library version: 2.5.6

## Steps To Reproduce
Build with podfile:  

```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'xxx' do
  # use_frameworks! 

  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"

  use_native_modules!

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
end
```

Debug.log from xcode : https://gist.github.com/iRyusa/02843a2634c5a69c17c4d965d4184bb7

What I've tried:
- Remove Pods & reinstall
- Clean Build Build 
- Reinstall everything (yarn+rn+xcode+cocoapods)

What I'll try: 
- Clean RN install from 0.61
- Downgrade to 0.60 (https://github.com/facebook/react-native/releases/tag/v0.61.0 0.61 has done some work about use_frameworks)

**Comment by iRyusa** [comment]
Well... sorry for the issue as I did migrate from 0.59 to 0.61 something fucked up with cocoapods, when removing the lib the next one (alphabetically speaking) will raise the same error.

**Comment by sanjayradadiya** [comment]
I am still having same issue 

**What I've tried:**
- Remove Pods & reinstall
- Clean Build Build
- Reinstall everything (yarn+rn+xcode+cocoapods)

![image](https://user-images.githubusercontent.com/16476120/69779776-24b58600-11cf-11ea-9cb3-b2af56eda107.png)

**Comment by makarkotlov** [comment]
Same issue here

**Comment by Venumteam** [comment]
same here

**Comment by iRyusa** [comment]
Most likely not related to this lib ! 

> most likely build lib search path that has been altered, revert it back to inherited

Try to revert everything to inherited ( i think newer version of cocoapods raise a warning)

**Comment by bwoodlt** [comment]
Having the same issue... were you able to fix this?

**Comment by andydev404** [comment]
Having the same issue...

**Comment by andydev404** [comment]
> Same issue here
> 
> UPDATE: check that `pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'` is added to your Podfile and you did pod install than open `xcworkspace` instead of `xcodeproj` in Xcode and try to build. Worked for me. RN^0.61.5. Here is my Podfile
> ![image](https://user-images.githubusercontent.com/32848434/70635038-42113800-1c44-11ea-8a6b-7b24aab3f63a.png)

This worked for me

**Comment by PomegranateApps** [comment]
@andydev404 I tried this but I'm still getting the same error.

**Comment by nihp** [comment]
Not worked for me any solution for that

**Comment by Venumteam** [comment]
use xcworkspace instead of xcodeproj, should work

**Comment by nihp** [comment]
I am using workspace only.

In the release mode only it not works.

Now I am getting 

`Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'DevSettings' could not be found. Verify that a module by this name is registered in the native binary.', reason: 'Unhandled JS Exception: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'DevSettings' could not be found. Verify that a module by this name is registered in the na..., stack:`

**Comment by tahirawan4** [comment]
> > Same issue here
> > UPDATE: check that `pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'` is added to your Podfile and you did pod install than open `xcworkspace` instead of `xcodeproj` in Xcode and try to build. Worked for me. RN^0.61.5. Here is my Podfile
> > ![image](https://user-images.githubusercontent.com/32848434/70635038-42113800-1c44-11ea-8a6b-7b24aab3f63a.png)
> 
> This worked for me, thanks

I did the same thing and worked for me too. Thanks

In my podfile `pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'` was missing, I have added in manually and run `pod install`

**Comment by master96** [comment]
Please check if your Pod file platform :ios, '11.0' matches with the minimum deployment target in the XCODE setting...

**Comment by olegderecha** [comment]
The version in pod file was `platform :ios, '11.0'`, but deployment version was `9.0`. Changed to `11.0` and the app could be achieved!
