### ISSUE TITLE
Invariant Violation: requireNativeComponent: "BVLinearGradient" was not found in the UIManager.

### ISSUE THREAD

**Issue by lovelope** [react-native-community/react-native-linear-gradient#444]
# Bug

After adding lib to a fresh `react-native@0.59.10` project, I got this error. For some reason, I can not upgrade react-native to 0.60 or above.
<details>
<summary>error detail</summary>
<pre><code>
Invariant Violation: requireNativeComponent: "BVLinearGradient" was not found in the UIManager.

This error is located at:
    in BVLinearGradient (at react-native-linear-gradient/index.android.js:85)
    in RCTView (at View.js:45)
    in View (at react-native-linear-gradient/index.android.js:84)
    in LinearGradient (at Test/index.js:14)
    in RCTView (at View.js:45)
    in View (at Test/index.js:13)
    in Test (at SceneView.js:17)
    in SceneView (at CardStack.js:455)
    in RCTView (at View.js:45)
    in View (at CardStack.js:454)
    in RCTView (at View.js:45)
    in View (at CardStack.js:453)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at Card.js:12)
    in Card (at PointerEventsContainer.js:39)
    in Container (at CardStack.js:498)
    in RCTView (at View.js:45)
    in View (at CardStack.js:414)
    in RCTView (at View.js:45)
    in View (at CardStack.js:413)
    in CardStack (at CardStackTransitioner.js:67)
    in RCTView (at View.js:45)
    in View (at Transitioner.js:142)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:41)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at community/index.js:72)
    in RCTView (at View.js:45)
    in View (at LayoutView.js:78)
    in LayoutView (at community/index.js:71)
    in Community (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)
getNativeComponentAttributes
    getNativeComponentAttributes.js:29:4
get
    ReactNativeViewConfigRegistry.js:104:25
createInstance
    ReactNativeRenderer-dev.js:3988:53
completeWork
    ReactNativeRenderer-dev.js:14437:12
completeUnitOfWork
    ReactNativeRenderer-dev.js:17094:10
performUnitOfWork
    ReactNativeRenderer-dev.js:17304:30
workLoop
    ReactNativeRenderer-dev.js:17316:41
renderRoot
    ReactNativeRenderer-dev.js:17417:15
performWorkOnRoot
    ReactNativeRenderer-dev.js:18423:17
performWork
    ReactNativeRenderer-dev.js:18324:24
performSyncWork
    ReactNativeRenderer-dev.js:18285:14
requestWork
    ReactNativeRenderer-dev.js:18169:19
scheduleWork
    ReactNativeRenderer-dev.js:17969:16
scheduleRootUpdate
    ReactNativeRenderer-dev.js:18642:15
render
    ReactNativeRenderer-dev.js:19512:20
renderApplication
    renderApplication.js:61:34
run
    AppState.js:51:4
runApplication
    AppState.js:121:18
__callFunction
    MessageQueue.js:366:47
<unknown>
    MessageQueue.js:106:26
__guard
    MessageQueue.js:314:10
callFunctionReturnFlushedQueue
    MessageQueue.js:105:17
callFunctionReturnFlushedQueue
    [native code]
</code></pre>
</details>

## Environment info

React native info output:

```bash
  React Native Environment Info:
    System:
      OS: macOS 10.15
      CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
      Memory: 28.99 MB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.19.1 - ~/.nvm/versions/node/v12.13.0/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
```

Library version: 2.5.6

## Steps To Reproduce

1.  `react-native init simpleRN5910 --version 0.59.10`
2. `cd simpleRN5910`
3. `yarn add react-native-linear-gradient`
4. `react-native link react-native-linear-gradient`
5. `yarn start`
6. I got this error even if I didn't change any code

Describe what you expected to happen:

1. working without error

**Comment by njacob1001** [comment]
You should to try reinstalling the apk, after you had made a clean in to build folder

**Comment by bearwmceo** [comment]
After installation `yarn add react-native-linear-gradient`, install pods:
`cd ios`
`pod install`

**Comment by lovelope** [comment]
> You should to try reinstalling the apk, after you had made a clean in to build folder
> 
> `cd android && ./gradlew cleanBuildCache`
> then
> `react-native run-android`

It's working in the new project, but it doesn't work in an existing project. I need to check the configuration of the existing project.

**Comment by lovelope** [comment]
> After installation `yarn add react-native-linear-gradient`, install pods:
> `cd ios`
> `pod install`

This method is not valid because there is no `Podfile` in the `react-native@0.59` project.

**Comment by neiker** [comment]
Same issue.

@lovelope do you find any fix?

**Comment by friederbluemle** [comment]
@lovelope - Thanks for the detailed issue description and steps to reproduce!

I have a very similar environment compared to yours (except that I'm still on Xcode 11.0, about to update).

I followed all steps, and had no issues. Everything works as expected (`react-native start/run-android/run-ios`). Can you please check if any other steps are missing? Otherwise this is most likely related to something else.

**Comment by gustavogialim** [comment]
Same problem with RN 0.61.4
**Obs:** In our case of versions> 60 we do not need the link command

**Comment by lovelope** [comment]
@neiker - Thanks for your solution, It's worked.

**Comment by AaronBedward** [comment]
Got this to work using expo-linear-gradient - https://docs.expo.io/versions/latest/sdk/linear-gradient/

**Comment by FrenchMajesty** [comment]
Still experiencing this issue on Android. I ended up simply added a conditional check and to not render a gradient if the user platform is Android.

**Comment by Kleinhummel** [comment]
+1

**Comment by shivo-ham** [comment]
duplicate #434

**Comment by zabojad** [comment]
Great. Having the same error on  a project running RN 0.61.5 and no solution so far...

**Comment by abdullateef97** [comment]
Having the same Issue on RN 0.63.2 react-native-linear-gradient 2.5.6 on an  Android Device

**Comment by AboutReact** [comment]
> After installation `yarn add react-native-linear-gradient`, install pods:
> `cd ios`
> `pod install`

Worked for me
![Screenshot 2020-10-03 at 12 39 42 AM](https://user-images.githubusercontent.com/54550555/94960797-1764d880-0511-11eb-8559-1b955e71994e.png)

**Comment by hu-qi** [comment]
> Having the same Issue on RN 0.63.2 react-native-linear-gradient 2.5.6 on an Android Device

Hello，have you solved the same problem？

**Comment by a1nouru** [comment]
@neiker thanks for the alternative import. Worked for me :)

**Comment by Prakharsaxena64** [comment]
I have solved this issue and the following steps giving below- 
1- Run  `cd android && ./gradlew cleanBuildCache`
2- Run `cd ios && pod install`
3- Run `yarn start` or `npm start`
4- Uninstall app from both (android and ios)  device and re-install them.
I hope it will help .
