### ISSUE TITLE
Ios Working Well , Android is not for button backgroundColors.

### ISSUE THREAD

**Issue by alicancelik** [react-native-community/react-native-linear-gradient#447]
# Bug
When i use linear-gradient for my backgroundColor, it is crash my button's colors.

## Environment info
- react-native: 0.61.1
- react-native-linear-gradient: 2.5.6

## Steps To Reproduce

1.react-native init simpleRN611 --version 0.61.1
2.cd simpleRN611
3.yarn add react-native-linear-gradient
4.react-native link react-native-linear-gradient
5.yarn start
6.Define <TouchableOpacity> with background color
...

Describe what you expected to happen:

1. I expected to see colors of buttons

![Screen Shot 2019-11-07 at 11 20 34](https://user-images.githubusercontent.com/26031105/68373463-09b5a000-0154-11ea-8563-273966c6303e.png)

**Comment by ramonhoyo** [comment]
I have a similar issue, 

When I try to use LinearGradient I got the next error.

![image](https://user-images.githubusercontent.com/22970814/74398631-b015df00-4dee-11ea-81c9-6fb87a233ef3.png)
