### ISSUE TITLE
How to animate the height?

### ISSUE THREAD

**Issue by Drzaln** [react-native-community/react-native-linear-gradient#449]
Hi, i can't animate the height of this library, i have wrap LinearGradient inside <Animated.View> but this is not successful, can anyone help me. Thank you

**Comment by mynameisguy** [comment]
You need to create animatedLinearGradient:
```
const AnimatedLinearGradient = createAnimatedComponent(LinearGradient);
```

**Comment by Drzaln** [comment]
> You need to create animatedLinearGradient:
> 
> ```
> const AnimatedLinearGradient = createAnimatedComponent(LinearGradient);
> ```

Just like that? All the props are same?

**Comment by mynameisguy** [comment]
exactly 👍

**Comment by Drzaln** [comment]
thank you, it's works
