### ISSUE TITLE
library not found for -lBVLinearGradient  RN 0.61.5

### ISSUE THREAD

**Issue by LeonidVeremchuk** [react-native-community/react-native-linear-gradient#452]
Hello. Have an issue with library autolonking

xCode version: Version 11.2.1 (11B500)
React Native version: 0.61.5

Steps :
1) Remove Podfile.lock
2) Remove Pods dir + Build clean && DeliveryData remove
3) Remove node_modules
4) yarn install
5) pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
6) cd ios && pod install

Error when archive.: 
```
ld: library not found for -lBVLinearGradient
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

P.S. debug build work as expected

**Comment by makarkotlov** [comment]
How did you solve this?

**Comment by marlti7** [comment]
How did you solve this?

**Comment by bwoodlt** [comment]
Having the same issue, spent at least two hours on this...

**Comment by bwoodlt** [comment]
@LeonidVeremchuk how did you fix this? Really need help with this. As you stated, `Debug` works for me also just not `Release`

**Comment by quantumproducer** [comment]
Bump. Urgent help needed. Debug works, release does not. I'm using the xcworkspace. I have that line about pointing to node modules already. @LeonidVeremchuk  @makarkotlov

**Comment by fkotsian** [comment]
> How did you solve this?
> 
> UPDATE: check that `pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'` is added to your Podfile and you did `pod install` than open `xcworkspace` instead of `xcodeproj` in Xcode and try to build. Worked for me

This works for some reason, check out https://stackoverflow.com/questions/24050012/error-library-not-found-for-after-putting-application-in-admob

**Comment by EhsanSarshar** [comment]
I have the same problem. any solution?

**Comment by morneluckybeard** [comment]
@EhsanSarshar  any luck? having the same problem.

**Comment by morneluckybeard** [comment]
Here's my solution. Hope it helps someone.

My problem arose cause I'm now using Cocoapods along with Fastlane for deploying to the stores.

Since I upgraded from react-native 0.59.10 -> .61.5 I've moved from manually linking the libraries to using Cocoapods in my project. My debug version was working fine as I was using .xcworkspace instead of the .xcodeproj file. 

I was using Fastlane to make deployments to the store and Fastlane was still pointing to the .xcodeproject instead of .xcworkspace thus it could not find any of the libraries. It just so happens to be that BVLinearGradient was the first library ( alphabetically ) that it could not find and it stopped the gym step process there.

I just updated my GymFile and Fastlane files to target .xcworkspace. and now my release version is working and submitting to the store.

**Comment by foxbit19** [comment]
I've solved adding `pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'` to `PodFile` and it worked.

Hope it helps!

**Comment by EhsanSarshar** [comment]
after upgrading from react-native@0.61.5 to react-native@0.62.2 I faced with error again :(

**Comment by jamithiran** [comment]
> How did you solve this?
> 
> UPDATE: check that `pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'` is added to your Podfile and you did `pod install` than open `xcworkspace` instead of `xcodeproj` in Xcode and try to build. Worked for me

Thank you, this solved it. Cheers

**Comment by ibrahimyolbir** [comment]
Hi @foxbit19  i added also "pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient' " to PodFile but its not working for me. do you have any idea. I am using RN 0-62.2 and when i run react-native run-ios I take his error   - react-native-linear-gradient (to unlink run: "react-native unlink react-native-linear-gradient")

**Comment by foxbit19** [comment]
@ibrahimyolbir same issue on RN 0.61.5 only on `run-ios` command. You can try to unlink the library as suggested but I'm not sure that this issue will disappear.

**Comment by LeonidVeremchuk** [comment]
I apologize for not commenting.
**"Ah sh*t, here we go again"...** 
So, first time I avoided this problem accidentally.

Today I switched to my old commit and this problem here.... what a day =(
How to fix:
1) Delete ~/Library/Developer/xCode/UserData and DerivedData
2) press Clean Project & Build - no result
3) in ios folder remove "build" folder
4) press Clean Project & Build - no result
5) under ios  remove folder 'Pods' & Podfile.lock  & pod install
6) Clean Project & Build - no result
7) had some coffee with a cigarette
8) press Clean Project with pressing 'option' button
9) No result damn.
10) ... waiting for indexing project...looking at wall... what happens knows only Steve...

Finally!!!! **Its very important!**  I just **close** the project and run under Project/ios/mypro.workport with a double tapping. And WOW -> this is fixed. 

Please don't blame me.. we live in a very strange world.  A bit of magic =) 

FYI: I think steps № 7 and 10 fixed this problem. 100% ;)

**Comment by EhsanSarshar** [comment]
so the general solution is to re create the ios folder.
by creating a brand new react native project and replacing current ios folder with newly created project ios folder

**Comment by tmaly1980** [comment]
None of these suggestions work for me.

**Comment by kumbhar-ketan** [comment]
Same here. None of the solution worked for me.

**Comment by RickameCua** [comment]
What fixed it for me was:
1. Removing pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient' on the Podfile
2. after pod install / npx pod-install I unlinked react-native-linear-gradient
3. opened ios/Project.xcworkspace and added libBVLinearGradient.a on Build Phases -> Link Binary With Libraries

Build Phases -> Link Binary With Libraries is now consists of:
![Screen Shot 2020-08-03 at 1 02 47 PM](https://user-images.githubusercontent.com/28285289/89147438-38e52a80-d589-11ea-950b-8bef903f7962.png)

I tried doing 1 and 3 it didn't work. I tried 2 and 3 still didn't work but when I tried 1, 2 and 3 everything worked out.
Hope this will help anyone.

**Comment by rekha-emids** [comment]
> Here's my solution. Hope it helps someone.
> 
> My problem arose cause I'm now using Cocoapods along with Fastlane for deploying to the stores.
> 
> Since I upgraded from react-native 0.59.10 -> .61.5 I've moved from manually linking the libraries to using Cocoapods in my project. My debug version was working fine as I was using .xcworkspace instead of the .xcodeproj file.
> 
> I was using Fastlane to make deployments to the store and Fastlane was still pointing to the .xcodeproject instead of .xcworkspace thus it could not find any of the libraries. It just so happens to be that BVLinearGradient was the first library ( alphabetically ) that it could not find and it stopped the gym step process there.
> 
> I just updated my GymFile and Fastlane files to target .xcworkspace. and now my release version is working and submitting to the store.

Where to update GymFile and Fastlane files?

**Comment by Chanondler** [comment]
Tried all the solutions, but build was not successful.
I am on react-native v 0.63.2

**Comment by EhsanSarshar** [comment]
@Chanondler have you tried cleaning up every thing.
removing node_modules
clearing the ios pods and cache
and every cleaning thing that you know

**Comment by Chanondler** [comment]
> @Chanondler have you tried cleaning up every thing.
> removing node_modules
> clearing the ios pods and cache
> and every cleaning thing that you know

Yes tried all the possible solutions. No success

**Comment by mack-wang** [comment]
I have tried all the above methods, but none of them worked.
Finally, I solved it like this:
File - Working Settings，don't use `Legacy Build System`
![image](https://user-images.githubusercontent.com/21222317/100492213-1c3ab700-3165-11eb-90e0-99e09c9e33d8.png)

**Comment by master96** [comment]
Please check if your Pod file platform :ios, '11.0' matches with the minimum deployment target in the XCODE setting...

**Comment by alencrowdbotics** [comment]
> Please check if your Pod file platform :ios, '11.0' matches with the minimum deployment target in the XCODE setting...

This fixed it for me.

**Comment by alencrowdbotics** [comment]
This fixed it for me

https://github.com/react-native-linear-gradient/react-native-linear-gradient/issues/452#issuecomment-750325305

**Comment by weihangChen** [comment]
> Please check if your Pod file platform :ios, '11.0' matches with the minimum deployment target in the XCODE setting...

took two nights before I came to your solution....it works

**Comment by PrantikMon** [comment]
> workport

Unfortunately, for me it is still showing me the same error. Though i also have tried all scenario that you have done. Specially everyone suggesting to open ios/MyProj. xcworkspace and i have opened that one only. Still it is not working. Same error.

**Comment by mack-wang** [comment]
您好，我已经收到你的来信。Hello,I have received your letter.                                       -----王乐城 mackwang

**Comment by yafiimo** [comment]
For anyone still getting this error, the solution in [this thread](https://github.com/react-native-community/upgrade-support/issues/50) worked for me. After completely removing react-native-linear-gradient from my project and rebuilding, I ended up with a similar looking error `Library not found for -lCocoaAsyncSocket`, which suggested that the original error, at least in my case, had nothing to do with react-native-linear-gradient. Hopefully that'll help if all else fails.

**Comment by mack-wang** [comment]
您好，我已经收到你的来信。Hello,I have received your letter.                                       -----王乐城 mackwang

**Comment by jaroslav009** [comment]
> Please check if your Pod file platform :ios, '11.0' matches with the minimum deployment target in the XCODE setting...

Genius!
