### ISSUE TITLE
Error while updating property 'colors' of a view managed by: BVLinearGradient

### ISSUE THREAD

**Issue by ntquang98** [react-native-community/react-native-linear-gradient#468]
# Bug
I using react native linear gradient in my react native project. It run correctly in IOS but fail in Android
![image](https://user-images.githubusercontent.com/30741286/78640885-a7b3bf00-78da-11ea-8c72-8446e4a4d738.png)

## Environment info

`react-native info` output:

```bash
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 761.85 MB / 7.89 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6308749
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0
```

Library version: 2.5.6

**Comment by joseananio** [comment]
Can you share some code?

Roughly based on the error, I assume you are passing a single color for the gradient. You should rather pass an array of colors; at least 2.
```
 <LinearGradient colors={[color1, color2, ...other_colors]} />
```

**Comment by lifekaizen** [comment]
Had the same problem, fixed it by doing a pod install ala `cd ios && pod install && cd ..` as suggested [here](https://github.com/react-native-community/react-native-linear-gradient/issues/444).

Installed with yarn and running react-native: 0.61.2.

**Comment by dielianhuachusai** [comment]
> Had the same problem, fixed it by doing a pod install ala `cd ios && pod install && cd ..` as suggested [here](https://github.com/react-native-community/react-native-linear-gradient/issues/444).
> 
> Installed with yarn and running react-native: 0.61.2.

It only support darwin os.
when I run "npx pod-install", the result was "CocoaPods is only supported on darwin machines".
I don't know how to fix it.
my os is opensuse 15.2 and I don't have any mac os machine

**Comment by jtstodola** [comment]
Has anyone found a solution for this on Android?

**Comment by grizz5555** [comment]
> Has anyone found a solution for this on Android?

Same question here

**Comment by xxvinciaxx** [comment]
You can check your code when you call LinearGradient
I fix this by add another color in colors, even I have not used that color later.

**Comment by chenyunshan** [comment]
I meet this issure too ,

**Comment by chenyunshan** [comment]
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 6.29 GB / 15.84 GB
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - D:\toolkit\node_global\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-22 | Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.30804.86 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_281
    Python: 2.7.8
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0

**Comment by xxvinciaxx** [comment]
> System:
> OS: Windows 10 10.0.18363
> CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
> Memory: 6.29 GB / 15.84 GB
> Binaries:
> Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
> Yarn: 1.22.10 - D:\toolkit\node_global\yarn.CMD
> npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
> Watchman: Not Found
> SDKs:
> Android SDK:
> Build Tools: 28.0.3, 29.0.2, 30.0.3
> System Images: android-22 | Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
> Android NDK: Not Found
> Windows SDK: Not Found
> IDEs:
> Android Studio: Not Found
> Visual Studio: 16.8.30804.86 (Visual Studio Community 2019)
> Languages:
> Java: 1.8.0_281
> Python: 2.7.8
> npmPackages:
> @react-native-community/cli: Not Found
> react: 17.0.1 => 17.0.1
> react-native: 0.64.0 => 0.64.0

你试试多传一个参数进去，这个报错是对colors传入了少于两个的参数，传俩，后面不调用也没关系的，可以把报错干掉

**Comment by dlewis2017** [comment]
Still having this issue as well, similar specs to here

> System:
> OS: Windows 10 10.0.18363
> CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
> Memory: 6.29 GB / 15.84 GB
> Binaries:
> Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
> Yarn: 1.22.10 - D:\toolkit\node_global\yarn.CMD
> npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
> Watchman: Not Found
> SDKs:
> Android SDK:
> Build Tools: 28.0.3, 29.0.2, 30.0.3
> System Images: android-22 | Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
> Android NDK: Not Found
> Windows SDK: Not Found
> IDEs:
> Android Studio: Not Found
> Visual Studio: 16.8.30804.86 (Visual Studio Community 2019)
> Languages:
> Java: 1.8.0_281
> Python: 2.7.8
> npmPackages:
> @react-native-community/cli: Not Found
> react: 17.0.1 => 17.0.1
> react-native: 0.64.0 => 0.64.0

**Comment by dlewis2017** [comment]
I had to use rgb instead of hex color codes and then it started working. I think the issue might be linked to how hex colors are mapped with react native's processColor: `colors={colors.map(processColor)}`, line ~86, in index.android.js of the react-native-linear-gradient folder in node_modules. The first color in the array is returning null. I didn't look too deep into it though.

So I changed this:
```
<LinearGradient useAngle={true} angle={45} angleCenter={{ x: 0.5, y: 0.5}} colors={['#eb82fd ', '#ed92fd', '#f1aafd']} >
...
</LinearGradient>
```
to this:
```
<LinearGradient useAngle={true} angle={45} angleCenter={{ x: 0.5, y: 0.5}} colors={['rgb(235, 130, 253)', 'rgb(237, 146, 253)', 'rgb(241, 170, 253)']} >
...
</LinearGradient>
```

**Comment by alenthalachira1998** [comment]
Check your color code correct or not  I had the same issue which now fixed

**Comment by Yogesh9725** [comment]
I got this same error when i do code like this.
colors={
                    item.id === 1
                      ? [COLORS.darkTheme, COLORS.lightTheme]
                      : ['transparent']
                  }
                  
So i just add same transparent colour and it's worked for me 

colors={
                    item.id === 1
                      ? [COLORS.darkTheme, COLORS.lightTheme]
                      : ['transparent', 'transparent']
                  }

**Comment by GustavoLucero** [comment]
I was able to fix this issue by hard coding the array of colors rather than importing them from a theme file. This is kinda weird because it works fine on other files where I'm using a constant from my theme file. 

Edit:
I reverted my "fix" and now it is working again with the constant from the theme file. God works in mysterious ways, I guess.
