### ISSUE TITLE
ld: library not found for -lBVLinearGradient

### ISSUE THREAD

**Issue by ibrahimyolbir** [react-native-community/react-native-linear-gradient#485]
# Bug report

## Summary
For some reasons i need to use File/Workspace Setting/Build system: **"Legacy Build System"** 
When i use **"Legacy Build system"** instead **"New build system"**  I get the following error
```
ld: warning: directory not found for option '-L-L/Users/ibrahimyolbir/Desktop/DidnerFonder/ios/build/Debug-iphonesimulator/BVLinearGradient'
ld: library not found for -lBVLinearGradient
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```
When i change Build system from **"Legacy Build System"**  to "New Build system  error disappears but as i  said for some reasons i need use **"Legacy Build System"**

* There is same result **react-native run-ios and building from Xcode**
 
[https://github.com/react-native-community/react-native-linear-gradient/issues?q=library+not+found](Similar Issues)
Here is similar issues but there is no solution in them that solves my problem

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 565.60 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version:      "react-native-linear-gradient": "^2.5.6",

## Steps to reproduce

 

1. Reinstall     "react-native-linear-gradient" and then pod 

2 Remove ios/pods&Podfile.lock, Remove ios/build&main.jsbundle 
3 Remove node_modules 
4. Remove ~/Library/Developer/xCode/UserData and DerivedData
5 Clean Project & Build
6 cd ios && pod deintegrate && pod install
7 create main.jsbundle

**Comment by jazsoft** [comment]
@ibrahimyolbir have you found any solution of it?

**Comment by ibrahimyolbir** [comment]
@jazsoft yes but i dont know if you have similar problem. my problem was with Appcenter ios build. and here is solution https://github.com/microsoft/appcenter-sdk-react-native/issues/837#issuecomment-641307171

and this is a general solution to the problem

https://github.com/react-native-community/react-native-linear-gradient/issues/454#issuecomment-613314623
