### ISSUE TITLE
ld: library not found for -lBVLinearGradient clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by kreondev** [react-native-community/react-native-linear-gradient#498]
ld: warning: directory not found for option '-L-L/Users/admin/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/BVLinearGradient'
ld: library not found for -lBVLinearGradient
clang: error: linker command failed with exit code 1 (use -v to see invocation)

`platform :ios, '9.0'

please provide suggestion or solution

**Comment by waheedakhtar694** [comment]
Having same issue.

**Comment by aryanagarwal15** [comment]
Having same issue

**Comment by waheedakhtar694** [comment]
I was able fix this issue by moving `$(inherited)` to bottom of the library search paths, Initially, It was on the top and moving to bottom works for me.

**Comment by notsubversion** [comment]
@waheedakhtar694 's fix didn't work for me. I had to bump up the iOS Deployment Target to 11.0 to match what I had in my Podfile. I had already updated target to 11.0 in Project, but I also had to update it under the build Target > Build Settings > Deployment > iOS Deployment Target.

**Comment by kreondev** [comment]
@waheedakhtar694  its working for me... thank you...

**Comment by Chanondler** [comment]
@waheedakhtar694 Its already there at the the bottom of Library Search Path

**Comment by pgqueme** [comment]
> I was able fix this issue by moving `$(inherited)` to bottom, Go to `Build Settings > Library search path`, Initially, `$(inherited)` was on the top and moving to bottom works for me.

This was the solution for me, thanks a lot!

**Comment by Sathit-Srisawat** [comment]
I fix this problem with Go to Build Settings > Library search path and remove "$(inherited)"  it work for me.

**Comment by 452MJ** [comment]
Just keep iOS development version to be same.

![image](https://user-images.githubusercontent.com/13673008/143518777-9d7d22b1-aaa5-4ed1-ad62-dafa41866ca9.png)
![image](https://user-images.githubusercontent.com/13673008/143518806-65cd0574-10bc-426d-aaeb-038078a01023.png)
