### ISSUE TITLE
Can't have gradient working without Xcode

### ISSUE THREAD

**Issue by alexmngn** [react-native-community/react-native-linear-gradient#61]
After running `rnpm link`, my project doesn't get the gradient while I run the `react-native run-ios` command. I get the following error in Chrome debugger:

> Warning: Native component for "BVLinearGradient" does not exist

It works fine if I run it from Xcode. Do you have any idea what causes the issue and if there is a way to fix it?

<img width="760" alt="screen shot 2016-02-26 at 19 27 41" src="https://cloud.githubusercontent.com/assets/4203845/13369102/20a6bd3e-dcbf-11e5-9f37-ec227577cc47.png">

**Comment by thomasbandit** [comment]
Similar thing for me with Android (using `react-native run-android` and emulating in genymotion). 

Following the readme's manual steps for Android, clearing the genymotion cache and restarting the emulator fixed it.

**Comment by brentvatne** [comment]
Seems related to https://github.com/brentvatne/react-native-linear-gradient/issues/67 -- can anyone submit a fix for this?

**Comment by chipe13** [comment]
I have the same error in my console. I installed this through the manual npm process (not rnpm) went through the steps from the docs putting everything needed into xcode. When I put the code in my project I get that same error "Warning: Native component for "BVLinearGradient" does not exist". Is there a fix for this yet?

**Comment by sulinixl** [comment]
This problem really bothered me for a long time.
Now I **maybe** find one solution accidently... and I hope it can help you guys......

I just edit `package.json`, and change the value of `name` from `'index'` to be `'index.ios.js'`.
Then restart everything, then `LinearGradient` works......

**I can't explain why**, you guys could try it and see what will happen...

**Comment by fantattitude** [comment]
I have the same problem and neither @chipe13's or @sulinixl's solutions seems to work for me… I'm going crazy here… 😩

**Comment by 1024kilobyte** [comment]
Same here

**Comment by Kaihuang724** [comment]
Has anyone figured this out? I'm running into the same exact error, tried installing with npm and then "rnpm link", and also tried rebuilding manually. The gradient works fine in Xcode, but not via react-native simulator.

**Comment by chocoluffy** [comment]
In my case, RN version 0.38.0, `react-native link react-native-linear-gradient` did the trick.

**Comment by ricardoamendes** [comment]
I got it working by linking the library libBVLinearGradient.a in Build Phases for **React.xcodeproj**. See below:
![screen shot 2017-01-13 at 11 56 02 am](https://cloud.githubusercontent.com/assets/247248/21914439/7c581234-d987-11e6-809f-713e67273520.png)

**Comment by mienaikoe** [comment]
I'm on an Android Device, and getting the same Error in adb: "Native component for "BVLinearGradient" does not exist"

Android Version 5.0.1
React Native 0.40.0

**Comment by ricardoamendes** [comment]
@mienaikoe 

This is my setup for Android. If it still does not work try `cd android && ./gradlew clean`.

_package.json_
**"react": "15.4.2"**
**"react-native": "0.40.0"**
**"react-native-linear-gradient": "^2.0.0"**

Emulator config

<img width="513" alt="screen shot 2017-01-14 at 5 40 52 pm" src="https://cloud.githubusercontent.com/assets/247248/21953012/e14dc20c-da80-11e6-8979-f6d73de328f8.png">

Result

<img width="412" alt="screen shot 2017-01-14 at 5 32 44 pm" src="https://cloud.githubusercontent.com/assets/247248/21953013/e7880d1c-da80-11e6-9595-2688a718b664.png">

**Comment by mienaikoe** [comment]
@ricardoamendes 
I had done all of those steps.
I discovered that the problem was that the gradient package was not linked when I ran `react-native link`. Therefore the class was never picked up. I've posted about it here:  https://github.com/react-native-community/react-native-linear-gradient/issues/106

**Comment by radex** [comment]
Hey! I'm closing this since it looks like a solved issue.
