### ISSUE TITLE
better docs on using locations, start, and end

### ISSUE THREAD

**Issue by Hendrixer** [react-native-community/react-native-linear-gradient#72]
I've played around with many different configs but can't seem to get what I desire which is: 
![gradient](https://cloud.githubusercontent.com/assets/2840504/14308540/a7361760-fb8b-11e5-8cf9-21a54e5d3875.png)

This is because I don't truly understand how the locations, start, end, and colors props work with each other.

**Comment by dgladkov** [comment]
Hi, while better docs are surely needed, I don't think it's possible to draw a gradient as shown in your example. Your example has multiple radial gradients which are not supported by the project at the moment. We have an open issue about it (#29) so if you are interested in implementing the feature, your help would be welcome:)

**Comment by Hendrixer** [comment]
awesome, thanks for the quick reply, and great work!

**Comment by greenteamer** [comment]
Hello, i'm realy don't understand what exactly mean "start", "end" and "location"
sart and end - coordinates?
for an hour trying to figure out by typing any options ... ((
thank's a lot for your job

**Comment by 9mm** [comment]
@greenteamer I can't find the issue right now on my phone, but search the github issues in this repo and somewhere the author explains exactly how to use it.

**Comment by kevinvangelder** [comment]
The interface, at least for iOS, has recently been updated so that start and end accept objects with an `x` and `y` value instead of the array, which is much easier to understand. For example: `start={{x: 0.0, y: 0.25}} end={{x: 0.5, y: 1.0}}`

**Comment by kevando** [comment]
wow @Hendrixer that is a really dope design!!

I was going to reply with some research I did, but I still have no fn clue what these props do.

**Comment by radex** [comment]
Hey! I'm closing this since it looks like a solved issue.
