### ISSUE TITLE
Setting border colour causes it to lose shape style

### ISSUE THREAD

**Issue by hasen6** [react-native-community/react-native-linear-gradient#80]
React Native 25.1

`circle: {
    width: 100,
    height: 100,
    borderRadius: 100/2,
    borderWidth: 1
  },`
![a](https://cloud.githubusercontent.com/assets/15882674/15265963/6d1a1338-19c7-11e6-955f-436c840be69e.png)
`circle: {
    width: 100,
    height: 100,
    borderRadius: 100/2,
    borderColor: '#fff', 
   borderWidth: 1
  },`
![b](https://cloud.githubusercontent.com/assets/15882674/15265967/795c6984-19c7-11e6-82dc-d39e609897f3.png)

**Comment by mxmtsk** [comment]
Setting `overflow: 'hidden';` fixed it for in my case but may not be a solution for everybody (absolute positioned elements etc)

**Comment by radex** [comment]
Hey! I'm closing this since it's a duplicate.
