### ISSUE TITLE
Only works around <Text> ?

### ISSUE THREAD

**Issue by blakeandrewwood** [react-native-community/react-native-linear-gradient#82]
I'm trying to use LinearGradient as a background, but it won't appear unless there is a text component directly in it.

Is it possible to make it fill in all of the screen space with flex: 1?

Even width: 100, height: 100 doesn't seem to do anything.

**Comment by dgladkov** [comment]
Here's a minimal example I used to create a `flex: 1` gradient component without children that works on both Android and iOS. Could you please try to reproduce the problem with the following example using the latest stable version of react-native and react-native-linear-gradient?

```javascript
import React from 'react';
import {
  AppRegistry,
  StyleSheet,
  View,
} from 'react-native';
import LinearGradient from 'react-native-linear-gradient';

const App = () => (
  <LinearGradient
    colors={['red', 'blue']}
    style={styles.gradient}
  />
);

const styles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
});

AppRegistry.registerComponent('ExampleApp', () => App);
```
Here's a screenshot:
![screenshot 2016-05-25 11 48 36](https://cloud.githubusercontent.com/assets/98132/15533843/f5a18f6a-226e-11e6-9983-30c86fe66138.png)

**Comment by Mark2xv** [comment]
Running exactly your code on React Native 0.27 I get the following result:

![image](https://cloud.githubusercontent.com/assets/3589798/15853132/1de9fac2-2ca4-11e6-9c70-1f8cf2f9e6ea.png)

**Comment by Mark2xv** [comment]
Whoops, nevermind :) Forgot to rebuild the iOS project... 
Weird that there's no warning for that.

**Comment by radex** [comment]
Hey! I'm closing this since this is a stale issue. If you believe it's still relevant to fix, post a comment and I'll reopen.
