### ISSUE TITLE
Error while updating property 'nativeBackgroundAndroid' of a view managed by: RCTView

### ISSUE THREAD

**Issue by DavyDeDurpel** [react-native-community/react-native-linear-gradient#84]
This error occurs when trying to run on API 19 (Android 4.4.2). Error occurs both on the device as on the simulator.
What is the minimal version that you are going to support for this module?

![error](https://cloud.githubusercontent.com/assets/12758369/15603722/aeccc7be-23fc-11e6-97b7-cd8a78a8f739.png)

**Comment by dgladkov** [comment]
This looks like either a react-native problem or a version mismatch between react-native JS and native code. Please try replacing `compile` lines for your dependencies in `android/app/build.gradle` with these

```groovy
compile(project(':react-native-linear-gradient')) {
    exclude group: 'com.facebook.react', module: 'react-native'
}
```
Possibly related react-native issue: https://github.com/facebook/react-native/issues/7748

**Comment by sudharsanmit** [comment]
I get the exact same error on API 16 (4.1.2). Works well on API 23 (Simulator).

**Comment by JeffreyGPalmer** [comment]
I believe that error comes from using _TouchableNativeFeedback_ with an API under 23.

**Comment by antoinerousseau** [comment]
indeed, error came from `TouchableNativeFeedback.Ripple(...)` in my case

**Comment by emrehayirci** [comment]
This error still exist on React Native 44.2

**Comment by radex** [comment]
Hey! I'm closing this since this is a stale issue. If you believe it's still relevant to fix, post a comment and I'll reopen.

**Comment by SamiChab** [comment]
See https://github.com/facebook/react-native/issues/9870#issuecomment-262855033
