### ISSUE TITLE
Cannot update with state

### ISSUE THREAD

**Issue by goredefex** [react-native-community/react-native-linear-gradient#92]
I am trying to have the linear gradient change its start and end points based on the intensity of another value. I am trying to change the prop values from

start={[0.5, 0]}
end={[0.5, 0.333333333]}

to

start={[0.5, 0]}
end={[0.5, 0.15]}

during runtime. The intensity is passed in as a prop by parent component object and so this officially doesn't make sense. By intensity I mean the 0.33333 versus 0.15 which is calculated and handed down. I know its not a state issue or that it's not rendering. I have stepped through every single component I have in this process and even put some debugging into your index.ios.js file in the node_modules folder and sure enough all values are making it into your {...otherProps} var just fine. I also have tried hard coding in those values and directly injecting them into a click action and still no go. I have NO IDEA why this is happening. So far out of a large app this is the only component that is not changing based on interactions. 

Thoughts?

**Comment by goredefex** [comment]
I have officially tried every combination of state or class level members to inject into the start and end props and no matter what they never ever change after the instantiation process. I cannot find where you have put this in your code so that it doesn't update but are you able to fix this?

If not I will be forced to try another plugin :(

**Comment by grifotv** [comment]
@goredefex I'm currently having the same issue: when updating the props `colors` and `locations` it gets rerendered, but when updating the props `start` and `end` it's completely ignored.

I worked around this issue by updating the `key` prop, to ensure it's rerendered - not ideal.

I'm using version `1.5.15`. I will upgrade to the latest version `2.0.0` and will let you know if it fixes this issue.

**Comment by grifotv** [comment]
I can confirm version `2.0.0` does update props `start` and `end` as expected.

You should use objects instead of arrays now. Eg: `start={{ x: 0, y:0 }}` and `end={{ x: 0, y:0 }}`.

I believe this issue is fixed and can be closed.

**Comment by goredefex** [comment]
yes thank you it is finally working for me now, much appreciated
